import type { ComponentMeta } from './types';

/**
 * Every component the kit ships, in Kitchen Sink display order. The single source for the Kitchen
 * Sink metadata, the registry tables in DESIGN_SYSTEM.md, llms.txt, the shadcn registry and the docs.
 * Demos live in components/devkit/sections/*.tsx, keyed by `id`. After editing, run
 * `npm run registry:build`.
 */
export const COMPONENTS: ComponentMeta[] = [
  {
    id: 'button',
    title: 'Button',
    exports: ['Button'],
    category: 'actions',
    files: ['components/ui/button.tsx'],
    notes: '`variant` default/secondary/outline/ghost/link/destructive · `size` sm/default/lg/icon · children are `<Text>`/`<Icon>`',
    api: '<Button variant? size? disabled?><Text>…</Text></Button>',
    caption: 'Children are Text and Icon, never a bare string. One primary button per screen.',
    aliases: ['cta', 'primary', 'secondary', 'outline', 'ghost', 'link', 'destructive', 'loading'],
  },
  {
    id: 'toggle',
    title: 'Toggle',
    exports: ['Toggle'],
    category: 'actions',
    files: ['components/ui/toggle.tsx'],
    notes: 'pressed two-state button',
    api: '<Toggle pressed onPressedChange><ToggleIcon as={…} /></Toggle>',
    aliases: ['pressed', 'two-state button'],
  },
  {
    id: 'toggle-group',
    title: 'Toggle group',
    exports: ['ToggleGroup'],
    category: 'actions',
    files: ['components/ui/toggle-group.tsx'],
    notes: '`type` single/multiple',
    api: '<ToggleGroup type="single|multiple" value onValueChange><ToggleGroupItem value … /></ToggleGroup>',
    caption: 'Use type="single" for a segmented control.',
    aliases: ['segmented', 'multi select buttons'],
  },
  {
    id: 'floating-button',
    title: 'Floating button',
    exports: ['FloatingButton'],
    category: 'actions',
    files: ['components/kit/floating-button.tsx'],
    notes: 'floats OVER the scroll (a Button flows with it) · Material calls it a FAB · `icon label? variant position` · one per screen',
    api: '<FloatingButton icon label? variant="primary|secondary" position="inline|bottom-right|bottom-center" />',
    caption: 'Floats over the scroll instead of sitting in it, so the screen’s one most important action stays reachable however far down you are. A Button flows with the content; this does not. Material calls it a FAB. One per screen.',
    aliases: ['fab', 'floating action button', 'plus', 'extended', 'add button'],
  },
  {
    id: 'icon-badge',
    title: 'Icon badge',
    exports: ['IconBadge'],
    category: 'actions',
    files: ['components/kit/icon-badge.tsx'],
    notes: 'icon button with unread count/dot · always labelled',
    api: '<IconBadge icon count? dot? accessibilityLabel />',
    caption: 'Header icon button with an unread count. The label announces the count for screen readers.',
    aliases: ['notification', 'bell', 'cart', 'unread count', 'icon button'],
  },
  {
    id: 'swipe-to-confirm',
    title: 'Swipe to confirm',
    exports: ['SwipeToConfirm'],
    category: 'actions',
    files: ['components/kit/swipe-to-confirm.tsx'],
    notes: 'drag past 85% commits · `tone` primary/destructive · reset via `key`',
    api: '<SwipeToConfirm label onConfirm confirmLabel? tone="primary|destructive" />',
    caption: 'For irreversible actions (submit, delete, pay). Reset by changing its key.',
    aliases: ['slide', 'drag', 'commit', 'high stakes'],
  },
  {
    id: 'action-grid',
    title: 'Action grid',
    exports: ['ActionGrid'],
    category: 'actions',
    files: ['components/kit/action-grid.tsx'],
    notes: 'the row of shortcuts under a screen hero · 3–4 `items`, one row only, last tile is "More"',
    api: '<ActionGrid items={[{icon,label,onPress,badge?}]} />',
    caption: 'The row of shortcuts under a screen hero. Keep it to one row — the last tile should be "More", not a second row.',
    aliases: ['quick actions', 'shortcuts', 'tiles', 'icon buttons'],
  },
  {
    id: 'input',
    title: 'Input',
    exports: ['Input'],
    category: 'inputs',
    files: ['components/ui/input.tsx'],
    notes: 'always with `Label`',
    api: '<Label htmlFor /> + <Input id placeholder keyboardType … />',
    caption: 'Pair every Input with a Label. Inputs stretch to their container.',
    aliases: ['text field', 'textfield', 'form'],
  },
  {
    id: 'label',
    title: 'Label',
    exports: ['Label'],
    category: 'inputs',
    files: ['components/ui/label.tsx'],
    notes: '`htmlFor` · own `onPress` on native',
    preview: false,
  },
  {
    id: 'textarea',
    title: 'Textarea',
    exports: ['Textarea'],
    category: 'inputs',
    files: ['components/ui/textarea.tsx'],
    notes: '',
    api: '<Textarea placeholder numberOfLines? />',
    aliases: ['multiline', 'message'],
  },
  {
    id: 'checkbox',
    title: 'Checkbox',
    exports: ['Checkbox'],
    category: 'inputs',
    files: ['components/ui/checkbox.tsx'],
    notes: '`checked onCheckedChange`',
    api: '<Checkbox checked onCheckedChange disabled? />',
    caption: 'On native the Label needs its own onPress to toggle.',
    aliases: ['tick', 'check'],
  },
  {
    id: 'radio-group',
    title: 'Radio group',
    exports: ['RadioGroup'],
    category: 'inputs',
    files: ['components/ui/radio-group.tsx'],
    notes: '`RadioGroupItem value id` · a `Label htmlFor` the same id names it',
    api: '<RadioGroup value onValueChange><RadioGroupItem value id /></RadioGroup>',
    aliases: ['single choice', 'option'],
  },
  {
    id: 'switch',
    title: 'Switch',
    exports: ['Switch'],
    category: 'inputs',
    files: ['components/ui/switch.tsx'],
    notes: 'settings on/off',
    api: '<Switch checked onCheckedChange />',
    caption: 'Settings-style on/off. For an action, use Toggle instead.',
    aliases: ['toggle', 'on off'],
  },
  {
    id: 'select',
    title: 'Select',
    exports: ['Select'],
    category: 'inputs',
    files: ['components/ui/select.tsx'],
    notes: 'pass safe-area `insets` to `SelectContent`',
    api: '<Select><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem label value /></SelectContent></Select>',
    caption: 'Pass safe-area insets to SelectContent so the sheet clears the home indicator.',
    aliases: ['dropdown', 'picker', 'menu'],
  },
  {
    id: 'filter-chip',
    title: 'Filter chip',
    exports: ['FilterChip', 'FilterChipRow'],
    category: 'inputs',
    files: ['components/kit/filter-chip.tsx'],
    notes: 'neutral-active chips',
    api: '<FilterChipRow><FilterChip label selected onPress icon? /></FilterChipRow>',
    caption: 'Selected state is inverted neutral, never the brand colour.',
    aliases: ['chip', 'tag filter', 'pill'],
  },
  {
    id: 'segmented-control',
    title: 'Segmented control',
    exports: ['SegmentedControl'],
    category: 'inputs',
    files: ['components/kit/segmented-control.tsx'],
    notes: '2–4 options, animated thumb',
    api: '<SegmentedControl segments={[{value,label}]} value onChange />',
    caption: '2–4 mutually exclusive options. For content panes use Tabs.',
    aliases: ['segment', 'ios', 'switcher'],
  },
  {
    id: 'search-field',
    title: 'Search field',
    exports: ['SearchField'],
    category: 'inputs',
    files: ['components/kit/search-field.tsx'],
    notes: 'Input + search icon + clear',
    api: '<SearchField value onChangeText placeholder />',
    aliases: ['search bar', 'find'],
  },
  {
    id: 'quantity-stepper',
    title: 'Quantity stepper',
    exports: ['QuantityStepper'],
    category: 'inputs',
    files: ['components/kit/quantity-stepper.tsx'],
    notes: '`min max step`',
    api: '<QuantityStepper value onChange min max step />',
    aliases: ['plus minus', 'counter', 'increment'],
  },
  {
    id: 'rating',
    title: 'Rating',
    exports: ['Rating'],
    category: 'inputs',
    files: ['components/kit/rating.tsx'],
    notes: 'stars · display (half stars, `showValue`, `count`) or input with `onChange` (44pt radio stars)',
    api: '<Rating value onChange? showValue? count? size? accessibilityLabel? />',
    caption: 'Show a score with the number beside it; ask for one after something is done (an order delivered), not in the middle of a task.',
    aliases: ['stars', 'review', 'score', 'feedback'],
  },
  {
    id: 'amount-input',
    title: 'Amount input',
    exports: ['AmountInput'],
    category: 'inputs',
    files: ['components/kit/amount-input.tsx'],
    notes: 'hero money field · `editable={false}` with keypad',
    api: '<AmountInput value onChangeText symbol helper? onMax? onToggleCurrency? error? editable? />',
    caption: 'Hero numeric entry. Set editable={false} when a NumericKeypad drives it.',
    aliases: ['money', 'currency', 'quantity', 'hero field', 'large number'],
  },
  {
    id: 'numeric-keypad',
    title: 'Numeric keypad',
    exports: ['NumericKeypad'],
    category: 'inputs',
    files: ['components/kit/numeric-keypad.tsx'],
    notes: '3×4 in-app keypad, keys on `bg-muted`',
    api: '<NumericKeypad value onChange maxLength? allowDecimal? />',
    caption: 'Replaces the system keyboard on full-screen amount entry. Long-press ⌫ clears.',
    aliases: ['keypad', 'pin pad', 'digits'],
  },
  {
    id: 'otp-input',
    title: 'OTP input',
    exports: ['OtpInput'],
    category: 'inputs',
    files: ['components/kit/otp-input.tsx'],
    notes: 'N-digit code, paste-aware',
    api: '<OtpInput length value onChange onComplete error? />',
    caption: 'Try 123456. Handles paste and backspace across cells.',
    aliases: ['code', 'verification', 'pin', '2fa', 'passcode'],
  },
  {
    id: 'password-input',
    title: 'Password input',
    exports: ['PasswordInput'],
    category: 'inputs',
    files: ['components/kit/password-input.tsx'],
    notes: 'Input + show/hide',
    api: '<PasswordInput value onChangeText />',
    aliases: ['secure', 'show hide', 'login'],
  },
  {
    id: 'selectable-card',
    title: 'Selectable card',
    exports: ['SelectableCard'],
    category: 'inputs',
    files: ['components/kit/selectable-card.tsx'],
    notes: 'card as a radio/checkbox choice',
    api: '<SelectableCard title description? icon? detail? selected onPress mode="radio|checkbox" />',
    caption: 'A whole card as a choice. Selection shows as a ring/check plus a tinted border, not colour alone.',
    aliases: ['radio card', 'option card', 'plan', 'choice'],
  },
  {
    id: 'slider',
    title: 'Slider',
    exports: ['Slider'],
    category: 'inputs',
    files: ['components/kit/slider.tsx'],
    notes: 'continuous/stepped · `tone` · `accessibilityLabel` names it',
    api: '<Slider value onChange min max step? tone? onChangeComplete? accessibilityLabel />',
    aliases: ['range', 'drag', 'percentage'],
  },
  {
    id: 'date-picker',
    title: 'Date picker',
    exports: ['DatePicker'],
    category: 'inputs',
    files: ['components/kit/date-picker.tsx'],
    notes: 'field trigger → Calendar in a Sheet',
    api: '<DatePicker value onChange placeholder? />',
    caption: 'Input-shaped trigger that opens a Calendar in a Sheet.',
    aliases: ['date', 'calendar field'],
  },
  {
    id: 'calendar',
    title: 'Calendar',
    exports: ['Calendar'],
    category: 'inputs',
    files: ['components/kit/calendar.tsx'],
    notes: 'month grid',
    api: '<Calendar value onChange />',
    aliases: ['month', 'day grid'],
  },
  {
    id: 'range-selector',
    title: 'Range selector',
    exports: ['RangeSelector'],
    category: 'inputs',
    files: ['components/kit/range-selector.tsx'],
    notes: 'trackless chart range (1D·1W·1M·1Y·ALL), active is a filled disc',
    api: '<RangeSelector options value onChange />',
    caption: 'For the time window over a chart. Use SegmentedControl instead when the options switch content rather than a period.',
    aliases: ['time range', 'chart range', '1D 1W 1M', 'period'],
  },
  {
    id: 'tabs',
    title: 'Tabs',
    exports: ['Tabs'],
    category: 'navigation',
    files: ['components/ui/tabs.tsx'],
    notes: 'in-page content switching',
    api: '<Tabs value onValueChange><TabsList><TabsTrigger value /></TabsList><TabsContent value /></Tabs>',
    caption: 'In-page content switching. App-level tabs are the Expo Router tab bar.',
    aliases: ['segmented', 'tab bar', 'content switch'],
  },
  {
    id: 'menubar',
    title: 'Menubar',
    exports: ['Menubar'],
    category: 'navigation',
    files: ['components/ui/menubar.tsx'],
    notes: 'web/desktop pattern',
    api: '<Menubar value onValueChange><MenubarMenu value><MenubarTrigger /><MenubarContent /></MenubarMenu></Menubar>',
    caption: 'Mostly a web/desktop pattern; prefer a DropdownMenu on phones.',
    aliases: ['menu', 'toolbar', 'desktop'],
  },
  {
    id: 'tab-bar',
    title: 'Tab bar',
    exports: ['TabBar', 'TabBarItem', 'tabIcon'],
    category: 'navigation',
    files: ['components/kit/tab-bar.tsx'],
    notes: 'custom bottom tab bar: opaque tints, label, active dot under the label',
    api: '<Tabs tabBar={(p) => <TabBar {...p} />}><Tabs.Screen options={{ title, tabBarIcon: tabIcon(HouseIcon) }} /></Tabs>',
    caption: 'The kit tab bar: opaque tints, label, and an active dot under the label so selection is not colour-only. TabBarItem is exported for custom bars.',
    aliases: ['bottom tabs', 'tab bar', 'active dot', 'navigation bar', 'tab icon'],
  },
  {
    id: 'kit-chip',
    title: 'Kit chip',
    exports: ['KitChip'],
    category: 'navigation',
    files: ['components/kit/kit-chip.tsx'],
    notes: 'scaffolding, not a product component: the way back to the kit from a sample. Not in the Kitchen Sink; delete it with the kit shell',
    preview: false,
    publish: false,
  },
  {
    id: 'stepper',
    title: 'Stepper',
    exports: ['Stepper'],
    category: 'navigation',
    files: ['components/kit/stepper.tsx'],
    notes: '`numbered` / `compact` flow progress',
    api: '<Stepper current total labels? variant="numbered|compact" />',
    aliases: ['progress steps', 'wizard', 'onboarding progress'],
  },
  {
    id: 'section-header',
    title: 'Section header',
    exports: ['SectionHeader'],
    category: 'navigation',
    files: ['components/kit/section-header.tsx'],
    notes: 'title + action, outside the card',
    api: '<SectionHeader title action? onAction? />',
    caption: 'Sits outside the card it introduces.',
    aliases: ['title', 'see all', 'heading row'],
  },
  {
    id: 'screen-header',
    title: 'Screen header',
    exports: ['ScreenHeader'],
    category: 'navigation',
    files: ['components/kit/screen-header.tsx'],
    notes: 'the in-body page title + intro · one per screen, first child of the ScrollView',
    api: '<ScreenHeader title subtitle? action? size="default|large" />',
    caption: 'One per screen, as the first child of the ScrollView. Section titles further down the page are SectionHeader, not this.',
    aliases: ['page title', 'heading', 'hero title', 'intro'],
  },
  {
    id: 'pager-dots',
    title: 'Pager dots',
    exports: ['PagerDots'],
    category: 'navigation',
    files: ['components/kit/pager-dots.tsx'],
    notes: '',
    api: '<PagerDots count activeIndex /> — HorizontalPager renders them for you',
    caption: 'Full-width slides: HorizontalPager with itemWidth = screen width. The dots are bound to the pager; use PagerDots alone only for a custom pager.',
    aliases: ['page indicator', 'carousel dots', 'onboarding slides', 'full-width pager'],
  },
  {
    id: 'horizontal-pager',
    title: 'Horizontal pager',
    exports: ['HorizontalPager'],
    category: 'navigation',
    files: ['components/kit/horizontal-pager.tsx'],
    notes: 'snap pager + dots',
    api: '<HorizontalPager itemWidth gap? showDots? onIndexChange?>{cards}</HorizontalPager>',
    caption: 'Peeking cards: itemWidth smaller than the screen shows the next card. Dots included.',
    aliases: ['carousel', 'swipe', 'slides', 'banner'],
  },
  {
    id: 'text',
    title: 'Text',
    exports: ['Text'],
    category: 'data',
    files: ['components/ui/text.tsx'],
    notes: 'the only Text · the scale is previewed in **Foundations › Typography**, not Components',
    preview: false,
  },
  {
    id: 'avatar',
    title: 'Avatar',
    exports: ['Avatar'],
    category: 'data',
    files: ['components/ui/avatar.tsx'],
    notes: 'image + fallback initials',
    api: '<Avatar alt><AvatarImage source /><AvatarFallback><Text /></AvatarFallback></Avatar>',
    caption: 'Default 48px. Image with initials fallback; size with size-8 / size-16; rounded-lg for a square.',
    aliases: ['profile', 'user', 'initials'],
  },
  {
    id: 'avatar-group',
    title: 'Avatar group',
    exports: ['AvatarGroup'],
    category: 'data',
    files: ['components/kit/avatar-group.tsx'],
    notes: 'overlapping avatars + "+N"',
    api: '<AvatarGroup items={[{id,initials,uri?}]} max? size? />',
    aliases: ['members', 'participants', 'stack', '+n'],
  },
  {
    id: 'badge',
    title: 'Badge',
    exports: ['Badge'],
    category: 'data',
    files: ['components/ui/badge.tsx'],
    notes: 'tag/pill/count · tint with semantic classes',
    api: '<Badge variant="default|secondary|destructive|outline"><Text /></Badge>',
    caption: 'Tint with a semantic class (bg-success + text-success-foreground), never a raw colour.',
    aliases: ['tag', 'chip', 'pill', 'count', 'status'],
  },
  {
    id: 'separator',
    title: 'Separator',
    exports: ['Separator'],
    category: 'data',
    files: ['components/ui/separator.tsx'],
    notes: '',
    api: '<Separator orientation="horizontal|vertical" />',
    aliases: ['divider', 'rule', 'hairline'],
  },
  {
    id: 'list-row',
    title: 'List row',
    exports: ['ListRow'],
    category: 'data',
    files: ['components/kit/list-row.tsx'],
    notes: 'ONE row · the canonical row · `last` on the final row · `select={{mode,selected}}` makes it a radio/checkbox row',
    api: '<ListRow leading title subtitle? value? sublabel? trailing? chevron? onPress? last? />',
    caption: 'The canonical row. Put rows inside a Card with px-4 py-0; mark the last one `last`.',
    aliases: ['row', 'cell', 'setting', 'menu item', 'list item'],
  },
  {
    id: 'list-group',
    title: 'List group',
    exports: ['ListGroup'],
    category: 'data',
    files: ['components/kit/list-group.tsx'],
    notes: 'the CONTAINER around rows: owns the title, dividers, footnote and card/plain surface · wraps ListRows and sets `last` for you · `variant` card/plain (plain = settings look)',
    api: '<ListGroup title? footnote? variant="card|plain">{rows}</ListGroup>',
    caption: 'Wraps ListRows and sets `last` on the final one for you. `plain` drops the card for the settings look; pair with ListRow `select` for radio or checkbox rows.',
    aliases: ['rows', 'settings list', 'grouped list', 'plain list', 'choice rows'],
  },
  {
    id: 'icon-circle',
    title: 'Icon circle',
    exports: ['IconCircle'],
    category: 'data',
    files: ['components/kit/icon-circle.tsx'],
    notes: 'leading icon well, row scale (≤44px) · `shape` circle/square · `tone`',
    api: '<IconCircle as size? shape="circle|square" tone? />',
    caption: 'Row scale only — 32–64px. `square` is the rounded-square well. At illustration scale (64px and up) use Spot instead.',
    aliases: ['icon well', 'avatar icon', 'leading icon'],
  },
  {
    id: 'summary-card',
    title: 'Summary card',
    exports: ['KeyValueList', 'SummaryCard'],
    category: 'data',
    files: ['components/kit/key-value-list.tsx'],
    notes: 'label/value rows, optionally in a Card',
    api: '<SummaryCard title? rows={[{label,value}]} /> · <KeyValueList rows />',
    aliases: ['key value', 'receipt', 'details', 'summary', 'confirmation'],
  },
  {
    id: 'stat-tile',
    title: 'Stat tile',
    exports: ['StatTile'],
    category: 'data',
    files: ['components/kit/stat-tile.tsx'],
    notes: 'KPI tile with delta',
    api: '<StatTile label value delta? icon? />',
    aliases: ['kpi', 'metric', 'dashboard'],
  },
  {
    id: 'percent-change',
    title: 'Percent change',
    exports: ['PercentChange'],
    category: 'data',
    files: ['components/kit/percent-change.tsx'],
    notes: 'signed % with trend icon',
    api: '<PercentChange value decimals? showIcon? />',
    aliases: ['delta', 'trend', 'up down'],
  },
  {
    id: 'progress-ring',
    title: 'Progress ring',
    exports: ['ProgressRing'],
    category: 'data',
    files: ['components/kit/progress-ring.tsx'],
    notes: 'circular determinate progress',
    api: '<ProgressRing value size? tone? accessibilityLabel?>{centre}</ProgressRing>',
    aliases: ['circular progress', 'goal', 'percent', 'donut'],
  },
  {
    id: 'status-dot',
    title: 'Status dot',
    exports: ['StatusDot'],
    category: 'data',
    files: ['components/kit/status-dot.tsx'],
    notes: '',
    api: '<StatusDot tone size />',
    aliases: ['indicator', 'online', 'presence'],
  },
  {
    id: 'timeline',
    title: 'Timeline',
    exports: ['Timeline'],
    category: 'data',
    files: ['components/kit/timeline.tsx'],
    notes: 'vertical status steps joined by a line · each `done` / `current` / `upcoming` with time and note',
    api: '<Timeline items={[{ title, time?, description?, state }]} tone? />',
    caption: 'For what already happened and what comes next (an order, a delivery, an application). A flow the person is filling in uses Stepper.',
    aliases: ['status steps', 'tracking', 'history', 'progress'],
  },
  {
    id: 'line-chart',
    title: 'Line chart',
    exports: ['LineChart'],
    category: 'data',
    files: ['components/kit/line-chart.tsx'],
    notes: 'interactive/sparkline · `area` · `onPointerChange`',
    api: '<LineChart data variant="interactive|sparkline" height tone area? onPointerChange? />',
    caption: 'Interactive variant reports the scrubbed point; render your own header from it.',
    aliases: ['sparkline', 'trend', 'time series', 'graph'],
  },
  {
    id: 'bar-chart',
    title: 'Bar chart',
    exports: ['BarChart'],
    category: 'data',
    files: ['components/kit/bar-chart.tsx'],
    notes: 'plain Views',
    api: '<BarChart data={[{label,value,className?}]} height showValues? />',
    aliases: ['bars', 'histogram', 'weekly'],
  },
  {
    id: 'donut-chart',
    title: 'Donut chart',
    exports: ['DonutChart', 'ChartLegend'],
    category: 'data',
    files: ['components/kit/donut-chart.tsx'],
    notes: 'ring + legend',
    api: '<DonutChart data size>{centre}</DonutChart> + <ChartLegend data />',
    aliases: ['pie', 'ring', 'allocation', 'breakdown'],
  },
  {
    id: 'value-header',
    title: 'Value header',
    exports: ['ValueHeader'],
    category: 'data',
    files: ['components/kit/value-header.tsx'],
    notes: 'hero figure + caption · `maskable` adds the eye toggle',
    api: '<ValueHeader value label? caption? captionTone? maskable? align? />',
    caption: 'The hero figure at the top of a screen. `maskable` adds the eye toggle for anything someone might not want visible over their shoulder.',
    aliases: ['balance', 'hero number', 'total', 'amount', 'mask', 'hide balance'],
  },
  {
    id: 'alert',
    title: 'Alert',
    exports: ['Alert'],
    category: 'feedback',
    files: ['components/ui/alert.tsx'],
    notes: 'inline, persistent · `variant` default/info/success/warning/destructive · `icon` · `onDismiss`/`action` make it a nudge',
    api: '<Alert icon variant="default|info|success|warning|destructive" onDismiss? action?><AlertTitle /><AlertDescription /></Alert>',
    caption: 'Inline and persistent, tinted by tone. For transient messages use Toast. `onDismiss` and `action` turn it into a nudge — never dismissible for an error the user must act on.',
    aliases: ['inline message', 'banner', 'callout', 'error', 'success'],
  },
  {
    id: 'progress',
    title: 'Progress',
    exports: ['Progress'],
    category: 'feedback',
    files: ['components/ui/progress.tsx'],
    notes: '0–100',
    api: '<Progress value={0–100} />',
    aliases: ['bar', 'loading', 'percent', 'determinate'],
  },
  {
    id: 'skeleton',
    title: 'Skeleton',
    exports: ['Skeleton'],
    category: 'feedback',
    files: ['components/ui/skeleton.tsx'],
    notes: '',
    api: '<Skeleton className="h-4 w-40" />',
    caption: 'Match the shape of the content it stands in for.',
    aliases: ['placeholder', 'shimmer', 'loading'],
  },
  {
    id: 'tooltip',
    title: 'Tooltip',
    exports: ['Tooltip'],
    category: 'feedback',
    files: ['components/ui/tooltip.tsx'],
    notes: '',
    api: '<Tooltip><TooltipTrigger asChild /><TooltipContent><Text /></TooltipContent></Tooltip>',
    aliases: ['hint', 'hover'],
  },
  {
    id: 'toast',
    title: 'Toast',
    exports: ['useToast', 'ToastProvider'],
    category: 'feedback',
    files: ['components/kit/toast.tsx'],
    notes: 'transient · `ToastProvider` is in the root layout',
    api: 'const toast = useToast(); toast.success("Saved") · .error · .warning · .info',
    caption: 'Transient, bottom-anchored, tap to dismiss. Persistent messages use Alert.',
    aliases: ['snackbar', 'notification', 'message', 'copied'],
  },
  {
    id: 'spinner',
    title: 'Spinner',
    exports: ['Spinner'],
    category: 'feedback',
    files: ['components/kit/spinner.tsx'],
    notes: 'themed ActivityIndicator · announced as "Loading"',
    api: '<Spinner size="small|large" tone="primary|foreground|muted" accessibilityLabel? />',
    aliases: ['loading', 'activity indicator'],
  },
  {
    id: 'empty-state',
    title: 'Empty state',
    exports: ['EmptyState'],
    category: 'feedback',
    files: ['components/kit/empty-state.tsx'],
    notes: '`default` / `compact`',
    api: '<EmptyState icon title subtitle? action? variant="default|compact" />',
    aliases: ['no results', 'nothing here', 'zero state'],
  },
  {
    id: 'success-screen',
    title: 'Success screen',
    exports: ['SuccessScreen'],
    category: 'feedback',
    files: ['components/kit/success-screen.tsx'],
    notes: 'the one success template',
    api: '<SuccessScreen title body? amount? amountSubtitle? loading?>{extra}</SuccessScreen>',
    caption: 'Use for EVERY success state: signup done, booking confirmed, order placed. Optional amount/subtitle when a value matters. Actions go in a StickyBottomBar below it.',
    aliases: ['done', 'confirmation', 'checkmark', 'complete'],
  },
  {
    id: 'card',
    title: 'Card',
    exports: ['Card'],
    category: 'layout',
    files: ['components/ui/card.tsx'],
    notes: 'never nest cards; titles sit outside · **flat — a shadow means pressable or floating**',
    api: '<Card><CardHeader><CardTitle /><CardDescription /></CardHeader><CardContent /><CardFooter /></Card>',
    caption: 'Never nest cards. Section titles sit outside the card.',
    aliases: ['surface', 'container', 'panel'],
  },
  {
    id: 'accordion',
    title: 'Accordion',
    exports: ['Accordion'],
    category: 'layout',
    files: ['components/ui/accordion.tsx'],
    notes: '',
    api: '<Accordion type="single|multiple" collapsible><AccordionItem value><AccordionTrigger /><AccordionContent /></AccordionItem></Accordion>',
    aliases: ['disclosure', 'expand', 'faq'],
  },
  {
    id: 'collapsible',
    title: 'Collapsible',
    exports: ['Collapsible'],
    category: 'layout',
    files: ['components/ui/collapsible.tsx'],
    notes: '',
    api: '<Collapsible><CollapsibleTrigger asChild /><CollapsibleContent /></Collapsible>',
    aliases: ['show more', 'expand'],
  },
  {
    id: 'sticky-bottom-bar',
    title: 'Sticky bottom bar',
    exports: ['StickyBottomBar'],
    category: 'layout',
    files: ['components/kit/sticky-bottom-bar.tsx'],
    notes: 'safe-area action bar under a ScrollView (`pb-32`)',
    api: '<StickyBottomBar transparent?>{buttons}</StickyBottomBar>',
    caption: 'Render after the ScrollView; give the scroll content pb-32. Children share the width equally.',
    aliases: ['cta bar', 'footer actions', 'safe area'],
  },
  {
    id: 'promo-card',
    title: 'Promo card',
    exports: ['PromoCard'],
    category: 'layout',
    files: ['components/kit/promo-card.tsx'],
    notes: 'tinted offer/nudge card · circular arrow CTA, dismiss X, generated art · one per screen',
    api: '<PromoCard title body? action? onDismiss? tone? seed? icon? />',
    caption: 'At most one per screen, and dismissible whenever it is promotional rather than required. The art is generated from the seed, so it needs no asset.',
    aliases: ['banner', 'upsell', 'announcement', 'offer', 'nudge'],
  },
  {
    id: 'footnote',
    title: 'Footnote',
    exports: ['Footnote'],
    category: 'layout',
    files: ['components/kit/footnote.tsx'],
    notes: 'small print / disclosure, last in the scroll',
    api: '<Footnote action?>{copy}</Footnote>',
    caption: 'Disclosures at the foot of a screen. Keep it last in the scroll, after the final section.',
    aliases: ['small print', 'legal', 'disclosure', 'terms', 'learn more'],
  },
  {
    id: 'prose',
    title: 'Prose',
    exports: ['Prose'],
    category: 'layout',
    files: ['components/kit/prose.tsx'],
    notes: "long-form text (articles, help, onboarding copy) at the theme's typeset: flow, measure, leading",
    api: '<Prose><Text variant="h3" /><Text variant="p" />…</Prose>',
    caption: 'Paragraphs are `Text variant="p"`; the flow is the only spacing between blocks. Text only inside.',
    aliases: ['typography', 'article', 'rich text', 'typeset', 'body copy'],
  },
  {
    id: 'dialog',
    title: 'Dialog',
    exports: ['Dialog'],
    category: 'overlays',
    files: ['components/ui/dialog.tsx'],
    notes: 'edits with a form',
    api: '<Dialog><DialogTrigger asChild /><DialogContent><DialogHeader /><DialogFooter /></DialogContent></Dialog>',
    caption: 'For edits with a form. Confirmations use AlertDialog.',
    aliases: ['modal', 'form modal'],
  },
  {
    id: 'alert-dialog',
    title: 'Alert dialog',
    exports: ['AlertDialog'],
    category: 'overlays',
    files: ['components/ui/alert-dialog.tsx'],
    notes: 'confirmations',
    api: '<AlertDialog>…<AlertDialogCancel /><AlertDialogAction /></AlertDialog>',
    aliases: ['confirm', 'destructive confirmation', 'are you sure'],
  },
  {
    id: 'popover',
    title: 'Popover',
    exports: ['Popover'],
    category: 'overlays',
    files: ['components/ui/popover.tsx'],
    notes: '',
    api: '<Popover><PopoverTrigger asChild /><PopoverContent side /></Popover>',
    caption: 'A small anchored panel for a quick edit or extra detail next to its trigger. For a full form use Dialog; for a list of actions use DropdownMenu.',
    aliases: ['bubble', 'anchored'],
  },
  {
    id: 'dropdown-menu',
    title: 'Dropdown menu',
    exports: ['DropdownMenu'],
    category: 'overlays',
    files: ['components/ui/dropdown-menu.tsx'],
    notes: 'pass `insets`',
    api: '<DropdownMenu><DropdownMenuTrigger asChild /><DropdownMenuContent insets><DropdownMenuItem /></DropdownMenuContent></DropdownMenu>',
    aliases: ['menu', 'actions', 'more'],
  },
  {
    id: 'context-menu',
    title: 'Context menu',
    exports: ['ContextMenu'],
    category: 'overlays',
    files: ['components/ui/context-menu.tsx'],
    notes: 'long-press',
    api: '<ContextMenu><ContextMenuTrigger /><ContextMenuContent insets><ContextMenuItem /></ContextMenuContent></ContextMenu>',
    aliases: ['long press', 'right click'],
  },
  {
    id: 'hover-card',
    title: 'Hover card',
    exports: ['HoverCard'],
    category: 'overlays',
    files: ['components/ui/hover-card.tsx'],
    notes: '',
    api: '<HoverCard><HoverCardTrigger asChild /><HoverCardContent insets /></HoverCard>',
    caption: 'Opens on press on native.',
    aliases: ['preview', 'profile card'],
  },
  {
    id: 'sheet',
    title: 'Sheet',
    exports: ['Sheet'],
    category: 'overlays',
    files: ['components/kit/sheet.tsx'],
    notes: 'bottom sheet shell',
    api: '<Sheet open onClose title? description?>{children}</Sheet>',
    caption: 'The base for OptionSheet and ActionSheet. Native mobile pattern; prefer over Dialog for pickers.',
    aliases: ['bottom sheet', 'drawer', 'modal sheet'],
  },
  {
    id: 'option-sheet',
    title: 'Option sheet',
    exports: ['OptionSheet'],
    category: 'overlays',
    files: ['components/kit/sheet.tsx'],
    notes: 'pick one of N',
    api: '<OptionSheet open onClose title options={[{value,label,description?,icon?}]} value onChange />',
    aliases: ['picker', 'select sheet', 'choose one'],
  },
  {
    id: 'action-sheet',
    title: 'Action sheet',
    exports: ['ActionSheet'],
    category: 'overlays',
    files: ['components/kit/sheet.tsx'],
    notes: 'list of actions + Cancel',
    api: '<ActionSheet open onClose title? items={[{label,icon?,destructive?,onPress}]} />',
    aliases: ['actions', 'more menu', 'share delete'],
  },
  {
    id: 'icon',
    title: 'Icon',
    exports: ['Icon'],
    category: 'media',
    files: ['components/ui/icon.tsx'],
    notes: 'lucide wrapper',
    api: '<Icon as={LucideIcon} size? className="text-…" />',
    caption: 'Lucide has 1,500+ icons. Colour with a text-* class; never import lucide outside this atom.',
    aliases: ['lucide', 'glyph', 'symbol'],
  },
  {
    id: 'image-tile',
    title: 'Image tile',
    exports: ['ImageTile'],
    category: 'media',
    files: ['components/kit/image-tile.tsx'],
    notes: 'rounded image · `seed` draws generated art when there is no `source`',
    api: '<ImageTile source? ratio? caption? fallbackIcon? />',
    caption: 'Rounded image with a muted placeholder while loading or when there is nothing to show.',
    aliases: ['image', 'photo', 'thumbnail', 'placeholder', 'cover'],
  },
  {
    id: 'aspect-ratio',
    title: 'Aspect ratio',
    exports: ['AspectRatio'],
    category: 'media',
    files: ['components/ui/aspect-ratio.tsx'],
    notes: '',
    api: '<AspectRatio ratio={16 / 9}>…</AspectRatio>',
    aliases: ['image', 'thumbnail', '16:9'],
  },
  {
    id: 'placeholder',
    title: 'Placeholder',
    exports: ['Placeholder'],
    category: 'media',
    files: ['components/kit/placeholder.tsx'],
    notes: 'deterministic abstract SVG art from a `seed` · the kit ships no raster imagery',
    api: '<Placeholder seed ratio? palette="chart|mono|primary" icon? />',
    caption: 'Stand-in imagery that never 404s. Drawn from theme colours, so it follows light/dark and re-brands with the tokens — use it instead of shipping placeholder files.',
    aliases: ['generated art', 'stand-in image', 'seeded', 'mock image', 'abstract'],
  },
  {
    id: 'spot',
    title: 'Spot',
    exports: ['Spot'],
    category: 'media',
    files: ['components/kit/spot.tsx'],
    notes: 'an icon at illustration scale (≥64px) · EmptyState, SuccessScreen and PermissionPrimer all use it',
    api: '<Spot icon size="md|lg|xl" tone? shape="circle|square" ring? />',
    caption: 'The whole illustration vocabulary: an icon at display scale. EmptyState, SuccessScreen and PermissionPrimer all render one. For a row’s leading slot use IconCircle — the boundary is 44px.',
    aliases: ['illustration', 'icon well', 'hero icon', 'empty state art'],
  },
  {
    id: 'photo-capture',
    title: 'PhotoCapture',
    exports: ['PhotoCapture'],
    category: 'native',
    files: ['components/kit/photo-capture.tsx'],
    notes: 'camera + library · falls back to a seeded `Placeholder`',
    api: '<PhotoCapture value? onChange? sources? shape="tile|avatar|wide" label? seed? simulate? />',
    caption: 'Tap to take or choose a photo. Falls back to generated art wherever there is no camera — the web preview, the simulator, a declined permission — so the screen still reads as filled.',
    aliases: ['camera', 'photo', 'image picker', 'upload', 'avatar photo', 'attachment'],
  },
  {
    id: 'code-scanner',
    title: 'CodeScanner',
    exports: ['CodeScanner'],
    category: 'native',
    files: ['components/kit/code-scanner.tsx'],
    notes: 'QR/barcode viewfinder · simulated emits a sample payload',
    api: '<CodeScanner onScan types? hint? ratio? continuous? simulatedValues? simulate? />',
    caption: 'QR and barcode viewfinder. Without a camera it shows the same framing overlay plus a button that emits a sample payload, so the flow behind it stays demonstrable.',
    aliases: ['qr', 'barcode', 'scan', 'camera viewfinder'],
  },
  {
    id: 'biometric-gate',
    title: 'BiometricGate',
    exports: ['BiometricGate', 'useBiometricAuth'],
    category: 'native',
    files: ['components/kit/biometric-gate.tsx'],
    notes: 'Face ID gate, or the hook for a single action · real only in a dev build',
    api: '<BiometricGate title? subtitle? prompt? locked? onUnlock? simulate?>…</BiometricGate> · useBiometricAuth()',
    caption: 'Hides its children until Face ID succeeds. Use the hook instead when you are confirming a single action. Real only in a dev build — Expo Go and the web simulate it.',
    aliases: ['face id', 'touch id', 'fingerprint', 'lock', 'unlock', 'biometrics'],
  },
  {
    id: 'permission-primer',
    title: 'PermissionPrimer',
    exports: ['PermissionPrimer'],
    category: 'native',
    files: ['components/kit/permission-primer.tsx'],
    notes: 'shown BEFORE the OS dialog · the skip is not optional',
    api: '<PermissionPrimer capability variant="inline|sheet" onAllow onSkip skipLabel? />',
    caption: 'Show this before the OS dialog, never instead of it. The skip is not optional: a prototype must never dead-end on a permission the viewer declined.',
    aliases: ['permission', 'allow', 'prompt', 'ask', 'privacy'],
  },
  {
    id: 'share',
    title: 'useShare',
    exports: ['useShare'],
    category: 'native',
    files: ['components/kit/share.ts'],
    notes: 'OS share sheet · copies to the clipboard on web',
    api: 'const { share } = useShare(); share({ message?, url?, title? })',
    caption: 'A hook, not a component — the trigger is an ordinary Button. Copies to the clipboard when the OS sheet is unavailable.',
    aliases: ['share sheet', 'send', 'export', 'copy link'],
  },
  {
    id: 'notify',
    title: 'useNotify',
    exports: ['useNotify', 'NotifyProvider'],
    category: 'native',
    files: ['components/kit/notify.tsx'],
    notes: 'in-app banner now (`delay: 0`), real OS notification when scheduled',
    api: 'const { notify } = useNotify(); notify({ title, body?, delay?, icon? })',
    caption: 'No delay draws the in-app banner, which looks the same everywhere and is what a demo needs. A delay also schedules the real OS notification when it can.',
    aliases: ['notification', 'alert', 'push', 'banner', 'reminder'],
  },
];
