// GENERATED by `npm run tokens:build` from tokens/tokens.json — do not edit by hand.
/** The theme uses the system font: no font variables (app/tokens.css falls back to the system stack). */
export const fontVariables = '';
