#!/usr/bin/env node
/**
 * scripts/shadcn-drift.mjs — which components/ui files still match shadcn/ui upstream (new-york-v4).
 *
 *   npm run registry:drift
 *
 * Writes registry/shadcn-forks.json, which registry:build reads: an unchanged file is published as a
 * dependency on shadcn's own item; a file the kit has changed is published as our own. Needs the network,
 * so it runs by hand (after `shadcn add` or an upgrade), not in CI.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SHADCN = 'https://ui.shadcn.com/r/styles/new-york-v4';
// The CLI rewrites registry-internal imports to the app's aliases on install; undo that before comparing.
const normalise = (s) =>
  s
    .replace(/@\/registry\/new-york-v4\/ui\//g, '@/components/ui/')
    .replace(/@\/registry\/new-york-v4\/hooks\//g, '@/hooks/')
    .replace(/@\/registry\/new-york-v4\/lib\//g, '@/lib/')
    .replace(/[ \t]+$/gm, '')
    .trim();

const result = {};
for (const file of readdirSync(join(root, 'components/ui')).sort()) {
  const name = file.replace(/\.tsx?$/, '');
  const res = await fetch(`${SHADCN}/${name}.json`);
  if (!res.ok || !res.headers.get('content-type')?.includes('json')) {
    result[name] = { upstream: false };
    continue;
  }
  const item = await res.json();
  const theirs = item.files?.find((f) => f.path.endsWith(`/${file}`))?.content ?? '';
  const ours = readFileSync(join(root, 'components/ui', file), 'utf8');
  result[name] = { upstream: true, forked: normalise(theirs) !== normalise(ours) };
}

writeFileSync(
  join(root, 'registry/shadcn-forks.json'),
  JSON.stringify({ $comment: 'GENERATED by `npm run registry:drift` — which components/ui files differ from shadcn/ui.', source: SHADCN, components: result }, null, 2) + '\n'
);
const forked = Object.entries(result).filter(([, r]) => r.forked).map(([n]) => n);
const same = Object.entries(result).filter(([, r]) => r.upstream && !r.forked).map(([n]) => n);
console.log(`registry:drift → ${forked.length} forked (${forked.join(', ') || '—'}), ${same.length} unchanged`);
