// GENERATED by `npm run tokens:build` from tokens/tokens.json — do not edit by hand.

/**
 * Semantic colours as hex, per scheme. Use ONLY where a className cannot reach:
 * SVG fills, chart strokes, canvas, platform props (a StatusBar, gradient stops). Everything
 * else styles with Tailwind classes (bg-primary, text-muted-foreground, …).
 */
export const THEME = {
  light: {
    background: '#ffffff',
    foreground: '#09090b',
    card: '#ffffff',
    cardForeground: '#09090b',
    popover: '#ffffff',
    popoverForeground: '#09090b',
    primary: '#2563eb',
    primaryForeground: '#ffffff',
    secondary: '#f4f4f5',
    secondaryForeground: '#18181b',
    muted: '#f4f4f5',
    mutedForeground: '#52525b',
    accent: '#f4f4f5',
    accentForeground: '#18181b',
    destructive: '#d92223',
    destructiveForeground: '#ffffff',
    success: '#15803d',
    successForeground: '#ffffff',
    warning: '#b45309',
    warningForeground: '#ffffff',
    info: '#0369a1',
    infoForeground: '#ffffff',
    border: '#e4e4e7',
    input: '#e4e4e7',
    ring: '#2563eb',
    sidebar: '#fafafa',
    sidebarForeground: '#09090b',
    sidebarPrimary: '#2563eb',
    sidebarPrimaryForeground: '#ffffff',
    sidebarAccent: '#f4f4f5',
    sidebarAccentForeground: '#18181b',
    sidebarBorder: '#e4e4e7',
    sidebarRing: '#2563eb',
    chart1: '#3b82f6',
    chart2: '#22c55e',
    chart3: '#f59e0b',
    chart4: '#ef4444',
    chart5: '#0ea5e9',
  },
  dark: {
    background: '#09090b',
    foreground: '#fafafa',
    card: '#18181b',
    cardForeground: '#fafafa',
    popover: '#18181b',
    popoverForeground: '#fafafa',
    primary: '#448bff',
    primaryForeground: '#09090b',
    secondary: '#27272a',
    secondaryForeground: '#fafafa',
    muted: '#27272a',
    mutedForeground: '#a1a1aa',
    accent: '#27272a',
    accentForeground: '#fafafa',
    destructive: '#fb504e',
    destructiveForeground: '#09090b',
    success: '#22c55e',
    successForeground: '#09090b',
    warning: '#fbbf24',
    warningForeground: '#09090b',
    info: '#0ea5e9',
    infoForeground: '#09090b',
    border: '#27272a',
    input: '#27272a',
    ring: '#448bff',
    sidebar: '#18181b',
    sidebarForeground: '#fafafa',
    sidebarPrimary: '#448bff',
    sidebarPrimaryForeground: '#09090b',
    sidebarAccent: '#27272a',
    sidebarAccentForeground: '#fafafa',
    sidebarBorder: '#27272a',
    sidebarRing: '#448bff',
    chart1: '#60a5fa',
    chart2: '#4ade80',
    chart3: '#fbbf24',
    chart4: '#f87171',
    chart5: '#38bdf8',
  },
} as const;

export type ThemeColors = typeof THEME.light;
export type ThemeColorName = keyof ThemeColors;

/** Non-colour primitives (px / ms) for the rare inline-style or Reanimated use. */
export const TOKENS = {
  space: {
    '0': 0,
    '1': 4,
    '2': 8,
    '3': 12,
    '4': 16,
    '5': 20,
    '6': 24,
    '8': 32,
    '10': 40,
    '12': 48,
    '16': 64,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 10,
    xl: 16,
    '2xl': 20,
    full: 9999,
    base: 10,
    control: 9999,
  },
  /** Lucide stroke width for icons (the Icon component's default; an explicit strokeWidth is relative to 2). */
  iconStroke: 2,
  /** Width of `border` in px. */
  borderWidth: 1,
  /** Control heights and padding (px) for the theme's density: h-control-sm, h-control, h-control-lg, px-control-x. */
  density: {"sm":40,"md":48,"lg":56,"x":20},
  /** The type scale at 16px; the theme's typeset multiplies it (text-* classes are already scaled). */
  fontSize: {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    '2xl': 24,
    '3xl': 30,
    '4xl': 36,
  },
  /** The typeset: body size (px) and its scale, running-text leading and its factor on the text sizes' line
   *  heights, and Prose's flow (em between blocks) and measure (characters per line). */
  typeset: {"size":16,"scale":1,"leading":1.75,"leadingFactor":1,"flow":1.25,"measure":70},
  fontFamily: {
    sans: "",
    mono: "Menlo",
    heading: "",
    body: "",
  },
  duration: {
    fast: 150,
    base: 200,
    slow: 300,
  },
  easing: {
    standard: [0.2,0,0,1],
    emphasized: [0.3,0,0,1],
    exit: [0.4,0,1,1],
  },
} as const;

/** The theme tokens.json was generated from (`kit-tokens theme apply`), or null. `edited`: theme tokens
 *  were changed by hand since. */
export const THEME_INFO: ThemeInfo | null = {
  "code": "pk1-29B3XC60003T",
  "name": "Default",
  "edited": false,
  "recipe": {
    "v": 1,
    "brand": "#2563eb",
    "neutral": "zinc",
    "radius": "lg",
    "controls": "pill",
    "font": {
      "heading": "system",
      "body": "system"
    },
    "stroke": "regular",
    "depth": "soft",
    "density": "comfortable",
    "border": "regular",
    "preset": "default"
  }
};

export type ThemeInfo = {
  code: string;
  name: string;
  edited: boolean;
  recipe: {
    v: number;
    brand: string;
    neutral: string;
    radius: string;
    controls: string;
    font: { heading: string; body: string };
    stroke: string;
    depth: string;
    density: string;
    border: string;
    preset?: string;
  };
};
