import type { ComponentMeta } from './types';

/**
 * Every component the web kit ships, in Kitchen Sink display order. The single source for the Kitchen
 * Sink, the registry tables in DESIGN_SYSTEM.md, llms.txt, the shadcn registry and the docs site.
 * Demos live in components/devkit/demos.tsx, keyed by `id`. After editing, run `npm run registry:build`.
 */
export const COMPONENTS: ComponentMeta[] = [
  // ---------- actions ----------
  {
    id: 'button',
    title: 'Button',
    exports: ['Button', 'buttonVariants'],
    category: 'actions',
    files: ['components/ui/button.tsx'],
    notes: '`variant` default/secondary/outline/ghost/link/destructive · `size` default/sm/lg/icon · `asChild` for links',
    api: '<Button variant? size? asChild?>Label</Button>',
    caption: 'One primary (default) button per view; everything else is secondary, outline or ghost. Wrap a Link with asChild instead of nesting.',
    aliases: ['cta', 'link button', 'icon button', 'destructive'],
  },
  {
    id: 'toggle',
    title: 'Toggle',
    exports: ['Toggle', 'toggleVariants'],
    category: 'actions',
    files: ['components/ui/toggle.tsx'],
    notes: 'a pressed/unpressed button (bold, mute, favourite)',
    api: '<Toggle pressed onPressedChange aria-label>…</Toggle>',
    aliases: ['pressed', 'favourite'],
  },
  {
    id: 'toggle-group',
    title: 'Toggle group',
    exports: ['ToggleGroup', 'ToggleGroupItem'],
    category: 'actions',
    files: ['components/ui/toggle-group.tsx'],
    notes: '`type` single (a segmented control) or multiple',
    api: '<ToggleGroup type="single" value onValueChange><ToggleGroupItem value>…</ToggleGroupItem></ToggleGroup>',
    caption: 'Use type="single" for a segmented control (view switchers, ranges). Selected state is neutral, not the brand colour.',
    aliases: ['segmented control', 'view switcher'],
  },

  // ---------- inputs ----------
  {
    id: 'input',
    title: 'Input',
    exports: ['Input'],
    category: 'inputs',
    files: ['components/ui/input.tsx'],
    notes: 'always with a `Label` · `aria-invalid` for errors',
    api: '<Label htmlFor="email">Email</Label><Input id="email" type="email" />',
    aliases: ['text field', 'form field'],
  },
  {
    id: 'label',
    title: 'Label',
    exports: ['Label'],
    category: 'inputs',
    files: ['components/ui/label.tsx'],
    notes: '`htmlFor` the field it names',
    preview: false,
  },
  {
    id: 'textarea',
    title: 'Textarea',
    exports: ['Textarea'],
    category: 'inputs',
    files: ['components/ui/textarea.tsx'],
    notes: 'multi-line text, grows with content',
    api: '<Textarea id placeholder rows? />',
  },
  {
    id: 'checkbox',
    title: 'Checkbox',
    exports: ['Checkbox'],
    category: 'inputs',
    files: ['components/ui/checkbox.tsx'],
    notes: '`checked onCheckedChange` · pick any',
    api: '<Checkbox id checked onCheckedChange /><Label htmlFor>…</Label>',
    caption: 'For picking any number of options. One-of-many is a RadioGroup; never mix the two in one group.',
  },
  {
    id: 'radio-group',
    title: 'Radio group',
    exports: ['RadioGroup', 'RadioGroupItem'],
    category: 'inputs',
    files: ['components/ui/radio-group.tsx'],
    notes: 'pick exactly one · `RadioGroupItem value id`',
    api: '<RadioGroup value onValueChange><RadioGroupItem value id /></RadioGroup>',
  },
  {
    id: 'switch',
    title: 'Switch',
    exports: ['Switch'],
    category: 'inputs',
    files: ['components/ui/switch.tsx'],
    notes: 'a setting that applies at once (no Save button)',
    api: '<Switch id checked onCheckedChange />',
  },
  {
    id: 'select',
    title: 'Select',
    exports: ['Select', 'SelectTrigger', 'SelectValue', 'SelectContent', 'SelectItem'],
    category: 'inputs',
    files: ['components/ui/select.tsx'],
    notes: 'one of 5–15 options in a form; fewer → RadioGroup, more → Command',
    api: '<Select value onValueChange><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value /></SelectContent></Select>',
    aliases: ['dropdown', 'picker'],
  },
  {
    id: 'date-picker',
    title: 'Date picker',
    exports: ['DatePicker'],
    category: 'inputs',
    files: ['components/kit/date-picker.tsx'],
    notes: 'one date in a form · field-styled button → Calendar in a Popover · `value onChange disabled?`',
    api: '<DatePicker id value onChange placeholder? disabled? />',
    caption: 'The placeholder says what the date is for (“Pick a due date”). Block days that cannot be chosen with `disabled` instead of erroring after.',
    aliases: ['date', 'calendar input', 'due date', 'deadline'],
  },
  {
    id: 'calendar',
    title: 'Calendar',
    exports: ['Calendar', 'CalendarDayButton'],
    category: 'inputs',
    files: ['components/ui/calendar.tsx'],
    notes: 'a month grid (react-day-picker) · `mode` single/range/multiple · use DatePicker for a form field',
    api: '<Calendar mode="single" selected onSelect disabled? />',
    caption: 'On its own for booking and availability views; inside a form, use DatePicker.',
    aliases: ['month', 'date range', 'availability'],
  },
  {
    id: 'slider',
    title: 'Slider',
    exports: ['Slider'],
    category: 'inputs',
    files: ['components/ui/slider.tsx'],
    notes: 'a value on a range · two thumbs for a range',
    api: '<Slider value onValueChange min max step aria-label />',
    aliases: ['range'],
  },

  // ---------- navigation ----------
  {
    id: 'app-shell',
    title: 'App shell',
    exports: ['AppShell'],
    category: 'navigation',
    files: ['components/kit/app-shell.tsx'],
    notes: 'sidebar of 4–8 destinations on desktop, a sheet on mobile · active item follows the URL',
    api: '<AppShell brand nav={[{href,label,icon}]} footer? topbar?>{page}</AppShell>',
    caption: 'The frame of every logged-in web app prototype. Put it in the prototype’s layout.tsx, not in each page.',
    aliases: ['sidebar', 'layout', 'navigation', 'dashboard shell'],
  },
  {
    id: 'tabs',
    title: 'Tabs',
    exports: ['Tabs', 'TabsList', 'TabsTrigger', 'TabsContent'],
    category: 'navigation',
    files: ['components/ui/tabs.tsx'],
    notes: 'switch views of the same thing in place; not page navigation',
    api: '<Tabs defaultValue><TabsList><TabsTrigger value /></TabsList><TabsContent value /></Tabs>',
  },
  {
    id: 'navigation-menu',
    title: 'Navigation menu',
    exports: ['NavigationMenu', 'NavigationMenuList', 'NavigationMenuItem', 'NavigationMenuTrigger', 'NavigationMenuContent', 'NavigationMenuLink', 'navigationMenuTriggerStyle'],
    category: 'navigation',
    files: ['components/ui/navigation-menu.tsx'],
    notes: 'a marketing site’s top nav with dropdown panels · not for app navigation (AppShell)',
    api: '<NavigationMenu><NavigationMenuList><NavigationMenuItem><NavigationMenuTrigger /><NavigationMenuContent /></NavigationMenuItem></NavigationMenuList></NavigationMenu>',
    caption: 'For marketing pages with grouped links. Hide it behind a Sheet on small screens; it does not collapse on its own.',
    aliases: ['mega menu', 'top nav', 'header menu'],
  },
  {
    id: 'breadcrumb',
    title: 'Breadcrumb',
    exports: ['Breadcrumb', 'BreadcrumbList', 'BreadcrumbItem', 'BreadcrumbLink', 'BreadcrumbPage', 'BreadcrumbSeparator'],
    category: 'navigation',
    files: ['components/ui/breadcrumb.tsx'],
    notes: 'where a detail page sits · the last item is the current page',
    api: '<Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink href /></BreadcrumbItem>…</BreadcrumbList></Breadcrumb>',
  },
  {
    id: 'pagination',
    title: 'Pagination',
    exports: ['Pagination', 'PaginationContent', 'PaginationItem', 'PaginationLink', 'PaginationPrevious', 'PaginationNext', 'PaginationEllipsis'],
    category: 'navigation',
    files: ['components/ui/pagination.tsx'],
    notes: 'pages of a long list or table · Previous/Next + page links · `isActive` on the current page',
    api: '<Pagination><PaginationContent><PaginationItem><PaginationPrevious href /></PaginationItem>…</PaginationContent></Pagination>',
    caption: 'Under a DataTable with more rows than fit. Say where the person is (“21–30 of 128”) next to it.',
    aliases: ['pages', 'next page', 'paging'],
  },
  {
    id: 'command',
    title: 'Command',
    exports: ['Command', 'CommandDialog', 'CommandInput', 'CommandList', 'CommandEmpty', 'CommandGroup', 'CommandItem'],
    category: 'navigation',
    files: ['components/ui/command.tsx'],
    notes: 'search-as-you-type list · `CommandDialog` for a ⌘K palette',
    api: '<Command><CommandInput /><CommandList><CommandGroup heading><CommandItem /></CommandGroup></CommandList></Command>',
    aliases: ['command palette', 'cmd k', 'search', 'combobox'],
  },

  // ---------- data ----------
  {
    id: 'data-table',
    title: 'Data table',
    exports: ['DataTable'],
    category: 'data',
    files: ['components/kit/data-table.tsx'],
    notes: 'sortable columns + built-in empty state · `columns rows rowKey caption?`',
    api: '<DataTable columns={[{key,header,cell?,sortValue?,align?}]} rows rowKey caption? />',
    caption: 'Every list of records in a prototype. Right-align numbers; give each column a sortValue only when sorting it helps.',
    aliases: ['table', 'grid', 'list'],
  },
  {
    id: 'table',
    title: 'Table',
    exports: ['Table', 'TableHeader', 'TableBody', 'TableRow', 'TableHead', 'TableCell', 'TableCaption'],
    category: 'data',
    files: ['components/ui/table.tsx'],
    notes: 'the primitive under DataTable; use it directly for small static tables',
  },
  {
    id: 'stat-tile',
    title: 'Stat tile',
    exports: ['StatTile'],
    category: 'data',
    files: ['components/kit/stat-tile.tsx'],
    notes: 'one KPI with a signed change · `invert` when down is good',
    api: '<StatTile label value delta? deltaLabel? invert? />',
    caption: 'Two to four across the top of a dashboard. The colour says good or bad, the arrow says up or down.',
    aliases: ['kpi', 'metric', 'number'],
  },
  {
    id: 'chart',
    title: 'Chart',
    exports: ['ChartContainer', 'ChartTooltip', 'ChartTooltipContent', 'ChartLegend', 'ChartLegendContent'],
    category: 'data',
    files: ['components/ui/chart.tsx'],
    notes: 'Recharts with the theme · series colours from `var(--chart-1)`…`--chart-5`',
    api: '<ChartContainer config={{ key: { label, color: "var(--chart-1)" } }}><BarChart data>…</BarChart></ChartContainer>',
    caption: 'Colour every series with a chart token through the config, never a hex.',
    aliases: ['graph', 'bar chart', 'line chart', 'recharts'],
  },
  {
    id: 'badge',
    title: 'Badge',
    exports: ['Badge', 'badgeVariants'],
    category: 'data',
    files: ['components/ui/badge.tsx'],
    notes: 'a status or tag · a status is an outline Badge with a coloured dot (`bg-success` …), the word in foreground text',
    api: '<Badge variant?>Label</Badge>',
    aliases: ['tag', 'pill', 'status'],
  },
  {
    id: 'avatar',
    title: 'Avatar',
    exports: ['Avatar', 'AvatarImage', 'AvatarFallback'],
    category: 'data',
    files: ['components/ui/avatar.tsx'],
    notes: 'image with initials fallback',
    api: '<Avatar><AvatarImage src alt /><AvatarFallback>AM</AvatarFallback></Avatar>',
  },
  {
    id: 'separator',
    title: 'Separator',
    exports: ['Separator'],
    category: 'data',
    files: ['components/ui/separator.tsx'],
    notes: 'a hairline between groups · prefer spacing',
  },

  // ---------- feedback ----------
  {
    id: 'alert',
    title: 'Alert',
    exports: ['Alert', 'AlertTitle', 'AlertDescription'],
    category: 'feedback',
    files: ['components/ui/alert.tsx'],
    notes: 'inline and persistent · `variant` default/destructive',
    api: '<Alert variant?><Icon /><AlertTitle /><AlertDescription /></Alert>',
  },
  {
    id: 'toast',
    title: 'Toast',
    exports: ['Toaster'],
    category: 'feedback',
    files: ['components/ui/sonner.tsx'],
    notes: 'transient confirmation · `toast()` from `sonner` · the Toaster is in the root layout',
    api: "import { toast } from 'sonner'; toast.success('Saved')",
    caption: 'For “done” and “undo”, not for errors that need action (use Alert next to the cause).',
    aliases: ['sonner', 'snackbar', 'notification'],
  },
  {
    id: 'progress',
    title: 'Progress',
    exports: ['Progress'],
    category: 'feedback',
    files: ['components/ui/progress.tsx'],
    notes: 'determinate 0–100',
    api: '<Progress value aria-label />',
  },
  {
    id: 'skeleton',
    title: 'Skeleton',
    exports: ['Skeleton'],
    category: 'feedback',
    files: ['components/ui/skeleton.tsx'],
    notes: 'the shape of content that is loading',
    api: '<Skeleton className="h-4 w-48" />',
    aliases: ['loading', 'placeholder'],
  },
  {
    id: 'empty-state',
    title: 'Empty state',
    exports: ['EmptyState'],
    category: 'feedback',
    files: ['components/kit/empty-state.tsx'],
    notes: 'nothing here yet, and the way out · `default` page / `compact` in a card',
    api: '<EmptyState icon title description? action? variant? />',
    caption: 'Every list and table needs one. Always offer the next step as a button.',
    aliases: ['zero state', 'no results'],
  },

  // ---------- layout ----------
  {
    id: 'page-header',
    title: 'Page header',
    exports: ['PageHeader'],
    category: 'layout',
    files: ['components/kit/page-header.tsx'],
    notes: 'title, description and actions · one per page, first in the content',
    api: '<PageHeader eyebrow? title description? actions? />',
    aliases: ['title', 'heading'],
  },
  {
    id: 'prose',
    title: 'Prose',
    exports: ['Prose'],
    category: 'layout',
    files: ['components/kit/prose.tsx'],
    notes: "long-form text (articles, docs, rendered markdown) at the theme's typeset: measure, leading, flow",
    api: '<Prose as?="div|article|section">{html}</Prose>',
    caption: 'Wrap text, not layout: headings, paragraphs, lists, quotes, code and tables. No cards or buttons inside.',
    aliases: ['typography', 'article', 'markdown', 'rich text', 'typeset'],
  },
  {
    id: 'card',
    title: 'Card',
    exports: ['Card', 'CardHeader', 'CardTitle', 'CardDescription', 'CardAction', 'CardContent', 'CardFooter'],
    category: 'layout',
    files: ['components/ui/card.tsx'],
    notes: 'a raised surface for one group · never nest cards',
    api: '<Card><CardHeader><CardTitle /><CardDescription /></CardHeader><CardContent /></Card>',
  },
  {
    id: 'accordion',
    title: 'Accordion',
    exports: ['Accordion', 'AccordionItem', 'AccordionTrigger', 'AccordionContent'],
    category: 'layout',
    files: ['components/ui/accordion.tsx'],
    notes: 'FAQs and long optional detail',
    aliases: ['faq', 'disclosure'],
  },
  {
    id: 'collapsible',
    title: 'Collapsible',
    exports: ['Collapsible', 'CollapsibleTrigger', 'CollapsibleContent'],
    category: 'layout',
    files: ['components/ui/collapsible.tsx'],
    notes: 'one show/hide region',
  },
  {
    id: 'scroll-area',
    title: 'Scroll area',
    exports: ['ScrollArea', 'ScrollBar'],
    category: 'layout',
    files: ['components/ui/scroll-area.tsx'],
    notes: 'a fixed-height region that scrolls on its own',
    preview: false,
  },

  // ---------- overlays ----------
  {
    id: 'dialog',
    title: 'Dialog',
    exports: ['Dialog', 'DialogTrigger', 'DialogContent', 'DialogHeader', 'DialogTitle', 'DialogDescription', 'DialogFooter', 'DialogClose'],
    category: 'overlays',
    files: ['components/ui/dialog.tsx'],
    notes: 'a short task on top of the page (an edit form)',
    api: '<Dialog><DialogTrigger asChild /><DialogContent><DialogHeader><DialogTitle /></DialogHeader>…</DialogContent></Dialog>',
  },
  {
    id: 'alert-dialog',
    title: 'Alert dialog',
    exports: ['AlertDialog', 'AlertDialogTrigger', 'AlertDialogContent', 'AlertDialogAction', 'AlertDialogCancel'],
    category: 'overlays',
    files: ['components/ui/alert-dialog.tsx'],
    notes: 'confirm something destructive · name the action on the button',
    caption: 'The confirm button says what happens (“Delete project”), never “OK”.',
    aliases: ['confirm'],
  },
  {
    id: 'sheet',
    title: 'Sheet',
    exports: ['Sheet', 'SheetTrigger', 'SheetContent', 'SheetHeader', 'SheetTitle', 'SheetDescription', 'SheetFooter'],
    category: 'overlays',
    files: ['components/ui/sheet.tsx'],
    notes: 'a side panel: filters, a record’s details, mobile navigation · `side`',
    aliases: ['drawer', 'side panel'],
  },
  {
    id: 'drawer',
    title: 'Drawer',
    exports: ['Drawer', 'DrawerTrigger', 'DrawerContent', 'DrawerHeader', 'DrawerTitle', 'DrawerDescription', 'DrawerFooter', 'DrawerClose'],
    category: 'overlays',
    files: ['components/ui/drawer.tsx'],
    notes: 'a bottom sheet you can drag down (vaul) · mobile-first quick actions and filters',
    api: '<Drawer><DrawerTrigger asChild /><DrawerContent><DrawerHeader><DrawerTitle /></DrawerHeader>…<DrawerFooter /></DrawerContent></Drawer>',
    caption: 'Phone-sized web flows: filters, a quick form, a share menu. On desktop use Dialog or Sheet.',
    aliases: ['bottom sheet', 'action sheet', 'swipe'],
  },
  {
    id: 'popover',
    title: 'Popover',
    exports: ['Popover', 'PopoverTrigger', 'PopoverContent'],
    category: 'overlays',
    files: ['components/ui/popover.tsx'],
    notes: 'a small panel anchored to a control',
  },
  {
    id: 'dropdown-menu',
    title: 'Dropdown menu',
    exports: ['DropdownMenu', 'DropdownMenuTrigger', 'DropdownMenuContent', 'DropdownMenuItem', 'DropdownMenuLabel', 'DropdownMenuSeparator'],
    category: 'overlays',
    files: ['components/ui/dropdown-menu.tsx'],
    notes: 'actions on a thing (row menu, account menu) · `variant="destructive"` items last',
    aliases: ['menu', 'more', 'kebab'],
  },
  {
    id: 'tooltip',
    title: 'Tooltip',
    exports: ['Tooltip', 'TooltipTrigger', 'TooltipContent'],
    category: 'overlays',
    files: ['components/ui/tooltip.tsx'],
    notes: 'names an icon button · never the only place information lives',
  },

  // ---------- marketing ----------
  {
    id: 'hero',
    title: 'Hero',
    exports: ['Hero'],
    category: 'marketing',
    files: ['components/kit/hero.tsx'],
    notes: 'one promise, one primary action · `media` for a product shot, omit for centred',
    api: '<Hero eyebrow? title description? actions? media? />',
    caption: 'The title is the promise in the customer’s words. One primary button.',
    aliases: ['header', 'banner', 'landing'],
  },
  {
    id: 'feature-grid',
    title: 'Feature grid',
    exports: ['FeatureGrid'],
    category: 'marketing',
    files: ['components/kit/feature-grid.tsx'],
    notes: '3–6 short blocks · `columns` 2/3',
    api: '<FeatureGrid features={[{icon,title,description}]} columns? />',
    caption: 'Say what changes for the customer, not what the feature is called.',
    aliases: ['features', 'benefits'],
  },
  {
    id: 'pricing-card',
    title: 'Pricing card',
    exports: ['PricingCard'],
    category: 'marketing',
    files: ['components/kit/pricing-card.tsx'],
    notes: 'one plan · 2–4 side by side · `highlighted` on one',
    api: '<PricingCard name price period? description? features action highlighted? />',
    aliases: ['plan', 'pricing', 'tier'],
  },

  // ---------- ai ----------
  {
    id: 'chat-message',
    title: 'Chat message',
    exports: ['ChatMessage'],
    category: 'ai',
    files: ['components/kit/chat-message.tsx'],
    notes: 'one turn · user = bubble on the right, assistant = plain text on the left',
    api: '<ChatMessage role="user|assistant" initials?>{content}</ChatMessage>',
    caption: 'Assistant turns are documents, not bubbles: long answers stay readable.',
    aliases: ['chat', 'conversation', 'turn'],
  },
  {
    id: 'chat-composer',
    title: 'Chat composer',
    exports: ['ChatComposer'],
    category: 'ai',
    files: ['components/kit/chat-composer.tsx'],
    notes: 'Enter sends, Shift+Enter breaks · `busy` turns Send into Stop · `accept` turns on attachments (paperclip, drop, chips)',
    api: '<ChatComposer onSend={(text, files) => …} busy? onStop? placeholder? accept? maxFiles? />',
    caption: 'Turn on `accept` only when the assistant can use files; say which kinds (“image/*,.pdf”). Files can be reviewed and removed before sending.',
    aliases: ['prompt', 'input', 'message box', 'attachments', 'upload', 'file'],
  },
  {
    id: 'attachment-chip',
    title: 'Attachment chip',
    exports: ['AttachmentChip', 'formatBytes'],
    category: 'ai',
    files: ['components/kit/attachment-chip.tsx'],
    notes: 'a file in a conversation: icon by type, name, size · `onRemove` while composing',
    api: '<AttachmentChip file={{ name, size, type? }} onRemove? />',
    caption: 'ChatComposer shows these itself; use it to show the files in a sent message. Without `onRemove` it is read-only.',
    aliases: ['file', 'upload', 'attachment'],
  },
  {
    id: 'chat-thread-list',
    title: 'Chat thread list',
    exports: ['ChatThreadList'],
    category: 'ai',
    files: ['components/kit/chat-thread-list.tsx'],
    notes: 'past conversations, grouped by when · `threads activeId onSelect onNew?`',
    api: '<ChatThreadList threads={[{id,title,preview?,group?}]} activeId onSelect onNew? />',
    caption: 'Beside the conversation on desktop, in a Sheet on small screens. Title threads by their topic, not “New chat”.',
    aliases: ['history', 'conversations', 'chat sidebar', 'threads'],
  },
  {
    id: 'sources',
    title: 'Sources',
    exports: ['SourceList', 'CitedText', 'stripCitations'],
    category: 'ai',
    files: ['components/kit/sources.tsx'],
    notes: 'what an answer is based on · numbered chips with previews · `[n]` in text → inline citations',
    api: '<CitedText text="… [1]" sources={[{ title, meta?, snippet?, href? }]} /><SourceList sources />',
    caption: 'Cite whenever the answer uses the person’s data or a document. Stream the answer with stripCitations, then show CitedText and SourceList once it is complete.',
    aliases: ['citations', 'references', 'footnotes', 'grounding'],
  },
  {
    id: 'follow-up-suggestions',
    title: 'Follow-up suggestions',
    exports: ['FollowUpSuggestions'],
    category: 'ai',
    files: ['components/kit/follow-up-suggestions.tsx'],
    notes: 'next questions under the latest answer · picking one sends it',
    api: '<FollowUpSuggestions suggestions={["…"]} onSelect />',
    caption: 'Two to four, phrased as the person would ask them, only under the latest answer, and hidden while the assistant is answering.',
    aliases: ['suggested replies', 'quick replies', 'next questions', 'chips'],
  },
  {
    id: 'streaming-text',
    title: 'Streaming text',
    exports: ['StreamingText', 'useStreamingText'],
    category: 'ai',
    files: ['components/kit/streaming-text.tsx'],
    notes: 'an answer arriving · all at once under reduced motion · screen readers get it once',
    api: '<StreamingText text onDone? />',
    aliases: ['typing', 'stream', 'typewriter'],
  },
  {
    id: 'thinking-indicator',
    title: 'Thinking indicator',
    exports: ['ThinkingIndicator'],
    category: 'ai',
    files: ['components/kit/thinking-indicator.tsx'],
    notes: 'the model is working · say what it is doing when you can',
    api: '<ThinkingIndicator label? />',
    aliases: ['loading', 'typing indicator'],
  },
  {
    id: 'tool-call-card',
    title: 'Tool call card',
    exports: ['ToolCallCard'],
    category: 'ai',
    files: ['components/kit/tool-call-card.tsx'],
    notes: 'an action the assistant took · `status` running/done/error/stopped · details collapsed',
    api: '<ToolCallCard title status input? output? />',
    caption: 'Name the action in words (“Searched orders”), not the function name. A call the person cancelled is `stopped`, not `error`.',
    aliases: ['tool use', 'function call', 'action'],
  },
  {
    id: 'approval-card',
    title: 'Approval card',
    exports: ['ApprovalCard'],
    category: 'ai',
    files: ['components/kit/approval-card.tsx'],
    notes: 'consent before consequence · says what changes and whether it can be undone',
    api: '<ApprovalCard title description? details? onApprove onDeny />',
    caption: 'Ask before anything irreversible or costly. The title is the action as a sentence the person can say yes to.',
    aliases: ['confirm', 'human in the loop', 'permission'],
  },
];
