#!/usr/bin/env node
/**
 * tokens/build.mjs — turns tokens/tokens.json into everything the app reads.
 *
 *   npm run tokens:build
 *
 * Outputs (all GENERATED — never hand-edit):
 *   global.css                        CSS variables for NativeWind (:root light, .dark:root dark)
 *   lib/theme.ts                      TS mirror (hex) for the few places className can't reach
 *   tokens/generated/tailwind.theme.js  colours + radius for tailwind.config.js
 *   tokens/generated/figma-theme.mjs    input for tokens/push-figma.mjs
 *
 * Style Dictionary resolves {references}; this script handles the light/dark modes
 * (a semantic colour's $value is { light, dark }) and the output formats.
 */
import StyleDictionary from 'style-dictionary';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = JSON.parse(readFileSync(join(root, 'tokens/tokens.json'), 'utf8'));
const MODES = ['light', 'dark'];
const HEADER = 'GENERATED by `npm run tokens:build` from tokens/tokens.json — do not edit by hand.';

// ---------- helpers ----------------------------------------------------------

function isModed(value) {
  return value && typeof value === 'object' && !Array.isArray(value) && MODES.every((m) => m in value);
}

/** Return a copy of the token tree with every { light, dark } value collapsed to one mode. */
function forMode(node, mode) {
  if (Array.isArray(node) || node === null || typeof node !== 'object') return node;
  if ('$value' in node) return { ...node, $value: isModed(node.$value) ? node.$value[mode] : node.$value };
  return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, forMode(v, mode)]));
}

async function resolve(mode) {
  const sd = new StyleDictionary({
    tokens: forMode(source, mode),
    usesDtcg: true,
    log: { verbosity: 'silent' },
    platforms: { kit: { transforms: [] } },
  });
  await sd.hasInitialized;
  const { allTokens } = await sd.getPlatformTokens('kit');
  return allTokens;
}

function hexToHslTriplet(hex) {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) throw new Error(`Expected a 6-digit hex colour, got "${hex}"`);
  const n = parseInt(m[1], 16);
  const r = ((n >> 16) & 255) / 255;
  const g = ((n >> 8) & 255) / 255;
  const b = (n & 255) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }
  const round = (x) => Math.round(x * 10) / 10;
  return `${round(h * 360)} ${round(s * 100)}% ${round(l * 100)}%`;
}

const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

/** CSS variable name for a semantic token: semantic.color.card-foreground → card-foreground, semantic.radius.base → radius */
function cssName(token) {
  const parts = token.path.slice(1).filter((p) => p !== 'color');
  if (parts.at(-1) === 'base') parts.pop();
  return parts.join('-');
}

const semanticOf = (tokens) => tokens.filter((t) => t.path[0] === 'semantic');
const primitiveOf = (tokens) => tokens.filter((t) => t.path[0] === 'primitive');

// ---------- build ------------------------------------------------------------

const [light, dark] = await Promise.all(MODES.map(resolve));
const semLight = semanticOf(light);
const semDark = semanticOf(dark);
const prim = primitiveOf(light);
const isColor = (t) => t.$type === 'color';

// 1. global.css
function cssBlock(selector, tokens) {
  const lines = tokens.map((t) => {
    const name = cssName(t);
    if (isColor(t)) return `    --${name}: ${hexToHslTriplet(t.$value)};`;
    if (name === 'radius') return `    --${name}: ${t.$value / 16}rem;`;
    return `    --${name}: ${t.$value};`;
  });
  return `  ${selector} {\n${lines.join('\n')}\n  }`;
}
const css = `/* ${HEADER} */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
${cssBlock(':root', semLight)}

${cssBlock('.dark:root', semDark)}
}
`;
writeFileSync(join(root, 'global.css'), css);

// 2. tokens/generated/tailwind.theme.js
const colors = Object.fromEntries(semLight.filter(isColor).map((t) => [cssName(t), `hsl(var(--${cssName(t)}))`]));
const borderRadius = {
  sm: 'calc(var(--radius) - 4px)',
  md: 'calc(var(--radius) - 2px)',
  lg: 'var(--radius)',
  xl: 'calc(var(--radius) + 4px)',
  '2xl': 'calc(var(--radius) + 10px)',
};
mkdirSync(join(root, 'tokens/generated'), { recursive: true });
writeFileSync(
  join(root, 'tokens/generated/tailwind.theme.js'),
  `// ${HEADER}\nmodule.exports = ${JSON.stringify({ colors, borderRadius }, null, 2)};\n`
);

// 3. lib/theme.ts
function tsColorObject(tokens) {
  return tokens
    .filter(isColor)
    .map((t) => `    ${camel(cssName(t))}: '${t.$value.toLowerCase()}',`)
    .join('\n');
}
function tsGroup(prefix) {
  const entries = prim.filter((t) => t.path.slice(1, 1 + prefix.length).join('.') === prefix.join('.'));
  return entries
    .map((t) => {
      const key = t.path.slice(1 + prefix.length).join('-');
      const safe = /^[a-z_$][\w$]*$/i.test(key) ? key : `'${key}'`;
      return `    ${safe}: ${JSON.stringify(t.$value)},`;
    })
    .join('\n');
}
const radiusBase = semLight.find((t) => cssName(t) === 'radius').$value;
const ts = `// ${HEADER}
import { DarkTheme, DefaultTheme, type Theme } from 'expo-router/react-navigation';

/**
 * Semantic colours as hex, per scheme. Use ONLY where a className cannot reach:
 * SVG fills, chart strokes, native props (StatusBar, gradient stops). Everything
 * else styles with Tailwind classes (bg-primary, text-muted-foreground, …).
 */
export const THEME = {
  light: {
${tsColorObject(semLight)}
  },
  dark: {
${tsColorObject(semDark)}
  },
} as const;

export type ThemeColors = typeof THEME.light;
export type ThemeColorName = keyof ThemeColors;

/** Non-colour primitives (px / ms) for the rare inline-style or Reanimated use. */
export const TOKENS = {
  space: {
${tsGroup(['space'])}
  },
  radius: {
${tsGroup(['radius'])}
    base: ${radiusBase},
  },
  fontSize: {
${tsGroup(['font', 'size'])}
  },
  fontFamily: {
${tsGroup(['font', 'family'])}
  },
  duration: {
${tsGroup(['duration'])}
  },
  easing: {
${tsGroup(['easing'])}
  },
} as const;

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
`;
writeFileSync(join(root, 'lib/theme.ts'), ts);

// ---------- contrast gate ----------------------------------------------------
// Re-branding this file is the documented workflow, and a pleasant-looking brand
// colour will happily fail WCAG without anyone noticing. Every pairing the kit
// actually renders is checked here, and a failure stops the build.

const AA = 4.5; // WCAG 2.1 AA, normal text. Kit labels are 16px — not "large text".
const AA_NON_TEXT = 3; // WCAG 1.4.11, icons and other meaningful non-text.

/** The alpha values the kit actually tints with (bg-<tone>/10 etc). */
const TINTS = [0.1, 0.15, 0.2];
/** Tones that get used as ink — text-<tone> and coloured icons — not just as fills. */
const TONES = ['primary', 'success', 'warning', 'info', 'destructive'];

/** Composite `hex` at `alpha` over `base`, the way a /NN tint renders. */
function blend(hex, base, alpha) {
  const rgb = (h) => {
    const n = parseInt(h.replace('#', ''), 16);
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
  };
  const [f, b] = [rgb(hex), rgb(base)];
  const mix = f.map((c, i) => Math.round(alpha * c + (1 - alpha) * b[i]));
  return '#' + mix.map((c) => c.toString(16).padStart(2, '0')).join('');
}

function relativeLuminance(hex) {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) throw new Error(`Expected a 6-digit hex colour, got "${hex}"`);
  const n = parseInt(m[1], 16);
  const channel = (c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
  const r = channel(((n >> 16) & 255) / 255);
  const g = channel(((n >> 8) & 255) / 255);
  const b = channel((n & 255) / 255);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

function contrast(a, b) {
  const [hi, lo] = [relativeLuminance(a), relativeLuminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

/**
 * Every way the kit puts one token against another:
 *   1. a fill and its own -foreground label
 *   2. body and muted text on each surface
 *   3. a tone used as INK — text-<tone> and coloured icons — on the page and on a card
 *   4. a tone's icon sitting on that same tone's tint, as Alert and IconCircle do
 *
 * 3 and 4 are the ones that matter most for a re-brand: a colour can be a perfectly good
 * fill and still be unreadable as text, which is exactly how an amber warning gets in.
 */
function contrastFailures(tokens, mode) {
  const hex = Object.fromEntries(tokens.filter(isColor).map((t) => [cssName(t), t.$value]));
  const pairs = [];
  for (const name of ['primary', 'secondary', 'destructive', 'success', 'warning', 'info', 'accent', 'card', 'popover', 'muted']) {
    if (hex[name] && hex[`${name}-foreground`]) pairs.push([`${name}-foreground on ${name}`, hex[`${name}-foreground`], hex[name]]);
  }
  for (const surface of ['background', 'card', 'muted']) {
    if (hex['muted-foreground'] && hex[surface]) pairs.push([`muted-foreground on ${surface}`, hex['muted-foreground'], hex[surface]]);
    if (hex.foreground && hex[surface]) pairs.push([`foreground on ${surface}`, hex.foreground, hex[surface]]);
  }

  // A tone used as ink rather than as a fill.
  const inkPairs = [];
  for (const tone of TONES) {
    if (!hex[tone]) continue;
    for (const surface of ['background', 'card']) {
      if (hex[surface]) inkPairs.push([`text-${tone} on ${surface}`, hex[tone], hex[surface]]);
    }
  }

  // A tone's icon on that tone's own tint — Alert, IconCircle, SwipeToConfirm.
  const tintPairs = [];
  for (const tone of TONES) {
    if (!hex[tone] || !hex.background) continue;
    for (const alpha of TINTS) {
      tintPairs.push([`${tone} icon on ${tone}/${alpha * 100}`, hex[tone], blend(hex[tone], hex.background, alpha)]);
    }
  }

  const check = (list, threshold) =>
    list
      .map(([label, fg, bg]) => ({ label, fg, bg, ratio: contrast(fg, bg), threshold }))
      .filter((r) => r.ratio < threshold);

  return [...check(pairs, AA), ...check(inkPairs, AA), ...check(tintPairs, AA_NON_TEXT)].map(
    (r) => `  ${mode.padEnd(5)} ${r.label.padEnd(36)} ${r.ratio.toFixed(2)} / ${r.threshold}  (${r.fg} on ${r.bg})`
  );
}

const failures = [...contrastFailures(semLight, 'light'), ...contrastFailures(semDark, 'dark')];
if (failures.length) {
  console.error(
    `\ntokens:build FAILED — ${failures.length} colour pairing(s) below WCAG AA (${AA}:1):\n\n${failures.join('\n')}\n\n` +
      'Darken the fill, or flip its -foreground between neutral.0 and neutral.950.\n' +
      'A brightened accent (usually the dark theme) needs dark text, not white.\n'
  );
  process.exit(1);
}

// 4. tokens/generated/figma-theme.mjs — what push-figma.mjs mirrors into Figma Variables
const figmaColors = Object.fromEntries(
  semLight.filter(isColor).map((t, i) => [cssName(t), { light: t.$value.toLowerCase(), dark: semDark.filter(isColor)[i].$value.toLowerCase() }])
);
const num = (prefix, code) =>
  Object.fromEntries(
    prim
      .filter((t) => t.path.slice(1, 1 + prefix.length).join(".") === prefix.join(".") && typeof t.$value === "number")
      .map((t) => {
        const key = t.path.slice(1 + prefix.length).join("-");
        return [key, { value: t.$value, code: code(key) }];
      })
  );
const figmaNumbers = {
  radius: num(["radius"], (k) => `rounded-${k}`),
  space: num(["space"], (k) => `p-${k}`),
  "font-size": num(["font", "size"], (k) => `text-${k}`),
};
writeFileSync(
  join(root, "tokens/generated/figma-theme.mjs"),
  `// ${HEADER}\nexport const COLORS = ${JSON.stringify(figmaColors, null, 2)};\nexport const NUMBERS = ${JSON.stringify(figmaNumbers, null, 2)};\n`
);

console.log(
  `tokens:build → global.css (${semLight.length} vars × 2 modes), lib/theme.ts, tokens/generated/tailwind.theme.js · contrast AA ✓`
);
