#!/usr/bin/env node
/**
 * tokens/build.mjs — turns tokens/tokens.json into everything the app reads.
 *
 *   npm run tokens:build
 *
 * Outputs (all GENERATED — never hand-edit):
 *   global.css                        CSS variables for NativeWind (:root light, .dark:root dark)
 *   lib/theme.ts                      TS mirror (hex) for the few places className can't reach
 *   tokens/generated/tailwind.theme.js  colours + radius for tailwind.config.js
 *
 * Style Dictionary resolves {references}; this script handles the light/dark modes
 * (a semantic colour's $value is { light, dark }) and the output formats.
 */
import StyleDictionary from 'style-dictionary';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = JSON.parse(readFileSync(join(root, 'tokens/tokens.json'), 'utf8'));
const MODES = ['light', 'dark'];
const HEADER = 'GENERATED by `npm run tokens:build` from tokens/tokens.json — do not edit by hand.';

// ---------- helpers ----------------------------------------------------------

function isModed(value) {
  return value && typeof value === 'object' && !Array.isArray(value) && MODES.every((m) => m in value);
}

/** Return a copy of the token tree with every { light, dark } value collapsed to one mode. */
function forMode(node, mode) {
  if (Array.isArray(node) || node === null || typeof node !== 'object') return node;
  if ('$value' in node) return { ...node, $value: isModed(node.$value) ? node.$value[mode] : node.$value };
  return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, forMode(v, mode)]));
}

async function resolve(mode) {
  const sd = new StyleDictionary({
    tokens: forMode(source, mode),
    usesDtcg: true,
    log: { verbosity: 'silent' },
    platforms: { kit: { transforms: [] } },
  });
  await sd.hasInitialized;
  const { allTokens } = await sd.getPlatformTokens('kit');
  return allTokens;
}

function hexToHslTriplet(hex) {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) throw new Error(`Expected a 6-digit hex colour, got "${hex}"`);
  const n = parseInt(m[1], 16);
  const r = ((n >> 16) & 255) / 255;
  const g = ((n >> 8) & 255) / 255;
  const b = (n & 255) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  let h = 0;
  let s = 0;
  if (max !== min) {
    const d = max - min;
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
    else if (max === g) h = ((b - r) / d + 2) / 6;
    else h = ((r - g) / d + 4) / 6;
  }
  const round = (x) => Math.round(x * 10) / 10;
  return `${round(h * 360)} ${round(s * 100)}% ${round(l * 100)}%`;
}

const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

/** CSS variable name for a semantic token: semantic.color.card-foreground → card-foreground, semantic.radius.base → radius */
function cssName(token) {
  const parts = token.path.slice(1).filter((p) => p !== 'color');
  if (parts.at(-1) === 'base') parts.pop();
  return parts.join('-');
}

const semanticOf = (tokens) => tokens.filter((t) => t.path[0] === 'semantic');
const primitiveOf = (tokens) => tokens.filter((t) => t.path[0] === 'primitive');

// ---------- build ------------------------------------------------------------

const [light, dark] = await Promise.all(MODES.map(resolve));
const semLight = semanticOf(light);
const semDark = semanticOf(dark);
const prim = primitiveOf(light);
const isColor = (t) => t.$type === 'color';

// 1. global.css
function cssBlock(selector, tokens) {
  const lines = tokens.map((t) => {
    const name = cssName(t);
    if (isColor(t)) return `    --${name}: ${hexToHslTriplet(t.$value)};`;
    if (name === 'radius') return `    --${name}: ${t.$value / 16}rem;`;
    return `    --${name}: ${t.$value};`;
  });
  return `  ${selector} {\n${lines.join('\n')}\n  }`;
}
const css = `/* ${HEADER} */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
${cssBlock(':root', semLight)}

${cssBlock('.dark:root', semDark)}
}
`;
writeFileSync(join(root, 'global.css'), css);

// 2. tokens/generated/tailwind.theme.js
const colors = Object.fromEntries(semLight.filter(isColor).map((t) => [cssName(t), `hsl(var(--${cssName(t)}))`]));
const borderRadius = {
  sm: 'calc(var(--radius) - 4px)',
  md: 'calc(var(--radius) - 2px)',
  lg: 'var(--radius)',
  xl: 'calc(var(--radius) + 4px)',
  '2xl': 'calc(var(--radius) + 10px)',
};
mkdirSync(join(root, 'tokens/generated'), { recursive: true });
writeFileSync(
  join(root, 'tokens/generated/tailwind.theme.js'),
  `// ${HEADER}\nmodule.exports = ${JSON.stringify({ colors, borderRadius }, null, 2)};\n`
);

// 3. lib/theme.ts
function tsColorObject(tokens) {
  return tokens
    .filter(isColor)
    .map((t) => `    ${camel(cssName(t))}: '${t.$value.toLowerCase()}',`)
    .join('\n');
}
function tsGroup(prefix) {
  const entries = prim.filter((t) => t.path.slice(1, 1 + prefix.length).join('.') === prefix.join('.'));
  return entries
    .map((t) => {
      const key = t.path.slice(1 + prefix.length).join('-');
      const safe = /^[a-z_$][\w$]*$/i.test(key) ? key : `'${key}'`;
      return `    ${safe}: ${JSON.stringify(t.$value)},`;
    })
    .join('\n');
}
const radiusBase = semLight.find((t) => cssName(t) === 'radius').$value;
const ts = `// ${HEADER}
import { DarkTheme, DefaultTheme, type Theme } from 'expo-router/react-navigation';

/**
 * Semantic colours as hex, per scheme. Use ONLY where a className cannot reach:
 * SVG fills, chart strokes, native props (StatusBar, gradient stops). Everything
 * else styles with Tailwind classes (bg-primary, text-muted-foreground, …).
 */
export const THEME = {
  light: {
${tsColorObject(semLight)}
  },
  dark: {
${tsColorObject(semDark)}
  },
} as const;

export type ThemeColors = typeof THEME.light;
export type ThemeColorName = keyof ThemeColors;

/** Non-colour primitives (px / ms) for the rare inline-style or Reanimated use. */
export const TOKENS = {
  space: {
${tsGroup(['space'])}
  },
  radius: {
${tsGroup(['radius'])}
    base: ${radiusBase},
  },
  fontSize: {
${tsGroup(['font', 'size'])}
  },
  fontFamily: {
${tsGroup(['font', 'family'])}
  },
  duration: {
${tsGroup(['duration'])}
  },
  easing: {
${tsGroup(['easing'])}
  },
} as const;

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};
`;
writeFileSync(join(root, 'lib/theme.ts'), ts);

console.log(
  `tokens:build → global.css (${semLight.length} vars × 2 modes), lib/theme.ts, tokens/generated/tailwind.theme.js`
);
