const { hairlineWidth } = require('nativewind/theme');
// GENERATED by `npm run tokens:build` from tokens/tokens.json — colours, radius, border width, the
// theme's depth (shadow-sm/md/lg), density (control heights) and typeset (text sizes, Prose).
const tokenTheme = require('./tokens/generated/tailwind.theme.js');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  // Relative to this file, not the working directory, so the build is the same from the monorepo root.
  content: {
    relative: true,
    files: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './prototype/**/*.{ts,tsx}'],
  },
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: tokenTheme.colors,
      borderRadius: tokenTheme.borderRadius,
      borderWidth: {
        ...tokenTheme.borderWidth,
        hairline: hairlineWidth(),
      },
      boxShadow: tokenTheme.boxShadow,
      // Density: h-control-sm / h-control / h-control-lg (and min-h-*), px-control-x.
      height: tokenTheme.height,
      minHeight: tokenTheme.minHeight,
      width: tokenTheme.width,
      spacing: tokenTheme.spacing,
      // Typeset: text-xs…4xl at the theme's size and leading; leading-prose, gap-flow, max-w-measure (Prose).
      fontSize: tokenTheme.fontSize,
      lineHeight: tokenTheme.lineHeight,
      maxWidth: tokenTheme.maxWidth,
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  future: {
    hoverOnlyWhenSupported: true,
  },
  plugins: [require('tailwindcss-animate')],
};
