// GENERATED by `npm run tokens:build` from tokens/tokens.json — do not edit by hand.

/** Font files for expo-font's useFonts (app/_layout.tsx). Empty when the theme uses the system font. */
export const FONT_ASSETS = {};

/**
 * The family expo-font registers for each role and weight (null: the system font). Android does not pick a
 * weight of a custom font from fontWeight, so components/ui/text.tsx sets the family per weight.
 */
export const FONT_FAMILY: Record<'heading' | 'body', Record<number, string> | null> = {
  heading: null,
  body: null,
};
