#!/usr/bin/env node
/**
 * scripts/rnr-drift.mjs — which components/ui files still match react-native-reusables upstream.
 *
 *   npm run registry:drift
 *
 * Fetches https://reactnativereusables.com/r/nativewind/<name>.json for every file in components/ui,
 * normalises rnr's `@/registry/nativewind/` import prefix, and compares it with ours. Writes
 * registry/rnr-forks.json, which registry:build reads: an unchanged file is published as a dependency
 * on the rnr URL; a forked one is published as our own item. Needs the network, so it is run by hand
 * (after an rnr or SDK upgrade, and before publishing the registry), not in CI.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const RNR = 'https://reactnativereusables.com/r/nativewind';

const normalise = (s) =>
  s
    .replace(/@\/registry\/nativewind\//g, '@/')
    .replace(/[ \t]+$/gm, '')
    .trim();

const result = {};
for (const file of readdirSync(join(root, 'components/ui')).sort()) {
  const name = file.replace(/\.tsx?$/, '');
  const res = await fetch(`${RNR}/${name}.json`);
  if (!res.ok || !res.headers.get('content-type')?.includes('json')) {
    result[name] = { upstream: false };
    continue;
  }
  const item = await res.json();
  const theirs = item.files?.find((f) => f.path.endsWith(`/${file}`))?.content ?? '';
  const ours = readFileSync(join(root, 'components/ui', file), 'utf8');
  result[name] = { upstream: true, forked: normalise(theirs) !== normalise(ours) };
}

writeFileSync(
  join(root, 'registry/rnr-forks.json'),
  JSON.stringify(
    {
      $comment: 'GENERATED by `npm run registry:drift` — which components/ui files differ from react-native-reusables.',
      source: RNR,
      components: result,
    },
    null,
    2
  ) + '\n'
);
const forked = Object.entries(result).filter(([, r]) => r.forked).map(([n]) => n);
const same = Object.entries(result).filter(([, r]) => r.upstream && !r.forked).map(([n]) => n);
console.log(`registry:drift → ${forked.length} forked (${forked.join(', ')}), ${same.length} unchanged (${same.join(', ') || '—'})`);
