#!/usr/bin/env node
/**
 * kit-tokens — turns tokens/tokens.json into everything an app reads.
 *
 *   kit-tokens build    resolve, run the contrast gate, write every target in tokens.config.json
 *   kit-tokens check    same, but write nothing; exit 1 if any generated file is stale (CI)
 *   kit-tokens figma    mirror the tokens into Figma Variables (see push-figma.mjs)
 *   kit-tokens theme    apply, show or list themes (see lib/theme-cli.mjs)
 *   kit-tokens --version
 *
 *   --root <dir>        app root (default: cwd); every path in the config is relative to it
 *   --config <file>     default: tokens/tokens.config.json
 *
 * tokens.config.json: { "source": "tokens/tokens.json", "targets": { "<target>": { …options } } }
 * Targets live in ./targets/<name>.mjs and return [{ path, contents }]. All outputs are GENERATED —
 * never hand-edit them.
 */
import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { checkContrast, AA, describeTintLimits, textOnTintLimits } from './lib/contrast.mjs';
import { scanTintText } from './lib/scan.mjs';
import { loadTokens } from './lib/resolve.mjs';

const here = dirname(fileURLToPath(import.meta.url));

/** Flags that take a value; every other --flag is a boolean. */
const VALUE_FLAGS = new Set(['root', 'config']);

function parseArgs(argv) {
  const [command = 'build', ...rest] = argv;
  const flags = {};
  const positional = [];
  for (let i = 0; i < rest.length; i++) {
    if (!rest[i].startsWith('--')) positional.push(rest[i]);
    else if (VALUE_FLAGS.has(rest[i].slice(2))) flags[rest[i].slice(2)] = rest[++i];
    else flags[rest[i].slice(2)] = true;
  }
  return { command, flags, positional };
}

export async function run(argv = process.argv.slice(2)) {
  const { command, flags, positional } = parseArgs(argv);
  if (command === '--version' || command === '-v') {
    console.log(JSON.parse(readFileSync(join(here, 'package.json'), 'utf8')).version);
    return;
  }
  const root = resolve(flags.root ?? process.cwd());

  if (command === 'figma') {
    process.env.KIT_TOKENS_ROOT = root;
    await import(pathToFileURL(join(here, 'push-figma.mjs')).href);
    return;
  }
  if (command !== 'build' && command !== 'check' && command !== 'theme') {
    console.error(`kit-tokens: unknown command "${command}". Use build, check, theme or figma.`);
    process.exit(2);
  }

  const configPath = join(root, flags.config ?? 'tokens/tokens.config.json');
  if (!existsSync(configPath)) {
    console.error(`kit-tokens: no config at ${configPath}`);
    process.exit(2);
  }
  const config = JSON.parse(readFileSync(configPath, 'utf8'));
  const source = config.source ?? 'tokens/tokens.json';

  if (command === 'theme') {
    const { themeCommand } = await import('./lib/theme-cli.mjs');
    const rebuild = ['build', '--root', root, ...(flags.config ? ['--config', flags.config] : [])];
    return themeCommand({ positional, flags, root, sourcePath: join(root, source), config, build: () => run(rebuild) });
  }
  const ctx = await loadTokens(join(root, source));
  ctx.root = root;
  ctx.header = `GENERATED by \`npm run tokens:build\` from ${source} — do not edit by hand.`;

  const failures = checkContrast(ctx.colors, { strict: true });
  if (failures.length) {
    console.error(
      `\ntokens:build FAILED — ${failures.length} colour pairing(s) below WCAG AA (${AA}:1):\n\n${failures.join('\n')}\n\n` +
        'Darken the fill, or flip its -foreground between neutral.0 and neutral.950.\n' +
        'A brightened accent (usually the dark theme) needs dark text, not white.\n' +
        'Or let the theme generator fix it: `kit-tokens theme apply <code|preset>` keeps the hue and adjusts the lightness.\n'
    );
    process.exit(1);
  }

  // The palette passes; now the source: a tone's text on its own tint, beyond what this palette allows.
  if (config.scan?.length) {
    const limits = textOnTintLimits(ctx.colors);
    const problems = scanTintText(root, config.scan, limits);
    if (problems.length) {
      console.error(
        `\nkit-tokens: ${problems.length} class string(s) put a tone's text on its own tint below WCAG AA (${AA}:1):\n\n${problems.join('\n')}\n\n` +
          `This palette allows: ${describeTintLimits(limits)}.\n` +
          'Use text-foreground on the tint (let the tint, an icon or a dot carry the colour), or a lighter tint.\n' +
          'An element that holds only an icon may keep its tone: add a `kit-tokens-ignore tint-text` comment.\n'
      );
      process.exit(1);
    }
  }

  const files = [];
  for (const [name, options] of Object.entries(config.targets ?? {})) {
    const { default: target } = await import(pathToFileURL(join(here, 'targets', `${name}.mjs`)).href);
    files.push(...(await target(ctx, options ?? {})));
  }

  if (command === 'check') {
    const stale = files.filter((f) => {
      const path = join(root, f.path);
      return !existsSync(path) || readFileSync(path, 'utf8') !== f.contents;
    });
    if (stale.length) {
      console.error(`kit-tokens check: ${stale.length} generated file(s) out of date — run \`npm run tokens:build\`:\n${stale.map((f) => `  ${f.path}`).join('\n')}`);
      process.exit(1);
    }
    console.log(`kit-tokens check: ${files.length} files up to date · contrast AA ✓`);
    return;
  }

  for (const f of files) {
    const path = join(root, f.path);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, f.contents);
  }
  console.log(`tokens:build → ${files.map((f) => f.path).join(', ')} · contrast AA ✓`);
}

// npm runs bins through a symlink in node_modules/.bin, so compare real paths.
const isMain = () => {
  try {
    return realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
};
if (process.argv[1] && isMain()) await run();
